// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

// The series verb. Covers every read surface that goes through buildSeriesQuery
// today — series, point queries, the table view, cardinality, PromQL series and
// the 1/sec cache-invalidation log query (a tag-only series query: empty `what`,
// group by tag1). what[] carries data_model.DigestSelector kinds; an empty
// what[] is legal and means "grouped tags and timestamps only". by[] carries
// grouped tag indices; format.ShardTagIndex (-3) is legal and is answered from
// shard_num, not from storage.
//
// Row limit semantics: the aggregator executes with LIMIT row_limit+1, because
// LIMIT N cannot distinguish "exactly N rows" from truncation. If the extra row
// appears the call FAILS with row_limit — a partial series result is never
// returned and never cached by the API.
type StatshouseStoreQuerySeries struct {
	FieldsMask uint32
	Base       StatshouseStoreQueryBase
	What       []int32
	By         []int32
	// MinHost (TrueType) // Conditional: item.FieldsMask.0
	// MaxHost (TrueType) // Conditional: item.FieldsMask.1
	// table view; absent = unsorted
	// SortDesc (TrueType) // Conditional: item.FieldsMask.2
	// SortAsc (TrueType) // Conditional: item.FieldsMask.3
}

func (StatshouseStoreQuerySeries) TLName() string { return "statshouse.storeQuerySeries" }
func (StatshouseStoreQuerySeries) TLTag() uint32  { return 0x57cb1008 }

func (item *StatshouseStoreQuerySeries) SetMinHost(v bool) {
	if v {
		item.FieldsMask |= 1 << 0
	} else {
		item.FieldsMask &^= 1 << 0
	}
}
func (item *StatshouseStoreQuerySeries) IsSetMinHost() bool { return item.FieldsMask&(1<<0) != 0 }

func (item *StatshouseStoreQuerySeries) SetMaxHost(v bool) {
	if v {
		item.FieldsMask |= 1 << 1
	} else {
		item.FieldsMask &^= 1 << 1
	}
}
func (item *StatshouseStoreQuerySeries) IsSetMaxHost() bool { return item.FieldsMask&(1<<1) != 0 }

func (item *StatshouseStoreQuerySeries) SetSortDesc(v bool) {
	if v {
		item.FieldsMask |= 1 << 2
	} else {
		item.FieldsMask &^= 1 << 2
	}
}
func (item *StatshouseStoreQuerySeries) IsSetSortDesc() bool { return item.FieldsMask&(1<<2) != 0 }

func (item *StatshouseStoreQuerySeries) SetSortAsc(v bool) {
	if v {
		item.FieldsMask |= 1 << 3
	} else {
		item.FieldsMask &^= 1 << 3
	}
}
func (item *StatshouseStoreQuerySeries) IsSetSortAsc() bool { return item.FieldsMask&(1<<3) != 0 }

func (item *StatshouseStoreQuerySeries) Reset() {
	item.FieldsMask = 0
	item.Base.Reset()
	item.What = item.What[:0]
	item.By = item.By[:0]
}

func (item *StatshouseStoreQuerySeries) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b1111)
	item.Base.FillRandom(rg)
	BuiltinVectorIntFillRandom(rg, &item.What)
	BuiltinVectorIntFillRandom(rg, &item.By)
}

func (item *StatshouseStoreQuerySeries) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = item.Base.ReadTL1(w); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorIntReadTL1(w, &item.What); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorIntReadTL1(w, &item.By); err != nil {
		return w, err
	}
	return w, nil
}

func (item *StatshouseStoreQuerySeries) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreQuerySeries) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Base.WriteTL1(w)
	w = BuiltinVectorIntWriteTL1(w, item.What)
	w = BuiltinVectorIntWriteTL1(w, item.By)
	return w
}

func (item *StatshouseStoreQuerySeries) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1008); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreQuerySeries) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreQuerySeries) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1008)
	return item.WriteTL1(w)
}

func (item *StatshouseStoreQuerySeries) ReadResultTL1(w []byte, ret *StatshouseStoreSeriesResponse) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseStoreQuerySeries) WriteResultTL1(w []byte, ret StatshouseStoreSeriesResponse) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseStoreQuerySeries) ReadResultJSON(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, ret *StatshouseStoreSeriesResponse) error {
	if err := ret.ReadJSONGeneral(jctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseStoreQuerySeries) WriteResultJSON(w []byte, ret StatshouseStoreSeriesResponse) (_ []byte, err error) {
	return item.writeResultJSON(nil, w, ret)
}

func (item *StatshouseStoreQuerySeries) writeResultJSON(jctx *basictl.JSONWriteContext, w []byte, ret StatshouseStoreSeriesResponse) (_ []byte, err error) {
	w = ret.WriteJSONOpt(jctx, w)
	return w, nil
}

func (item *StatshouseStoreQuerySeries) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret StatshouseStoreSeriesResponse
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseStoreQuerySeries) ReadResultTL1WriteResultJSON(jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreSeriesResponse
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(jctx, w, ret)
	return r, w, err
}

func (item *StatshouseStoreQuerySeries) ReadResultJSONWriteResultTL1(jctx *basictl.JSONReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreSeriesResponse
	if err = item.ReadResultJSON(jctx, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseStoreQuerySeries) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries")
}

func (item *StatshouseStoreQuerySeries) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries")
}

func (item *StatshouseStoreQuerySeries) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries")
}

func (item *StatshouseStoreQuerySeries) ReadResultJSONWriteResultTL2(jctx *basictl.JSONReadContext, tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries")
}

func (item StatshouseStoreQuerySeries) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreQuerySeries) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreQuerySeries) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propBasePresented bool
	var propWhatPresented bool
	var propByPresented bool
	var propMinHostPresented bool
	var trueTypeMinHostValue bool
	var propMaxHostPresented bool
	var trueTypeMaxHostValue bool
	var propSortDescPresented bool
	var trueTypeSortDescValue bool
	var propSortAscPresented bool
	var trueTypeSortAscValue bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "base":
				if propBasePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "base")
				}
				propBasePresented = true
				if err := item.Base.ReadJSONGeneral(jctx, in); err != nil {
					return err
				}
			case "what":
				if propWhatPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "what")
				}
				propWhatPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.What); err != nil {
					return err
				}
			case "by":
				if propByPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "by")
				}
				propByPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.By); err != nil {
					return err
				}
			case "min_host":
				if propMinHostPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "min_host")
				}
				propMinHostPresented = true
				if err := Json2ReadBool(in, &trueTypeMinHostValue); err != nil {
					return err
				}
			case "max_host":
				if propMaxHostPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "max_host")
				}
				propMaxHostPresented = true
				if err := Json2ReadBool(in, &trueTypeMaxHostValue); err != nil {
					return err
				}
			case "sort_desc":
				if propSortDescPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "sort_desc")
				}
				propSortDescPresented = true
				if err := Json2ReadBool(in, &trueTypeSortDescValue); err != nil {
					return err
				}
			case "sort_asc":
				if propSortAscPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "sort_asc")
				}
				propSortAscPresented = true
				if err := Json2ReadBool(in, &trueTypeSortAscValue); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeQuerySeries", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propBasePresented {
		item.Base.Reset()
	}
	if !propWhatPresented {
		item.What = item.What[:0]
	}
	if !propByPresented {
		item.By = item.By[:0]
	}
	if trueTypeMinHostValue {
		item.FieldsMask |= 1 << 0
	}
	if trueTypeMaxHostValue {
		item.FieldsMask |= 1 << 1
	}
	if trueTypeSortDescValue {
		item.FieldsMask |= 1 << 2
	}
	if trueTypeSortAscValue {
		item.FieldsMask |= 1 << 3
	}
	if propMinHostPresented && !trueTypeMinHostValue && (item.FieldsMask&(1<<0) != 0) {
		return ErrorInvalidJSON("statshouse.storeQuerySeries", "field 'min_host' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 0 is 1")
	}
	if propMaxHostPresented && !trueTypeMaxHostValue && (item.FieldsMask&(1<<1) != 0) {
		return ErrorInvalidJSON("statshouse.storeQuerySeries", "field 'max_host' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 1 is 1")
	}
	if propSortDescPresented && !trueTypeSortDescValue && (item.FieldsMask&(1<<2) != 0) {
		return ErrorInvalidJSON("statshouse.storeQuerySeries", "field 'sort_desc' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 2 is 1")
	}
	if propSortAscPresented && !trueTypeSortAscValue && (item.FieldsMask&(1<<3) != 0) {
		return ErrorInvalidJSON("statshouse.storeQuerySeries", "field 'sort_asc' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 3 is 1")
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreQuerySeries) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreQuerySeries) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreQuerySeries) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"base":`...)
	w = item.Base.WriteJSONOpt(jctx, w)
	backupIndexWhat := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"what":`...)
	w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.What)
	if !(len(item.What) != 0) {
		w = w[:backupIndexWhat]
	}
	backupIndexBy := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"by":`...)
	w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.By)
	if !(len(item.By) != 0) {
		w = w[:backupIndexBy]
	}
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"min_host":true`...)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"max_host":true`...)
	}
	if item.FieldsMask&(1<<2) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"sort_desc":true`...)
	}
	if item.FieldsMask&(1<<3) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"sort_asc":true`...)
	}
	return append(w, '}')
}

func (item *StatshouseStoreQuerySeries) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreQuerySeries) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeQuerySeries", err.Error())
	}
	return nil
}

func (item *StatshouseStoreQuerySeries) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries"))
}

func (item *StatshouseStoreQuerySeries) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries")
}

// The series verb. Covers every read surface that goes through buildSeriesQuery
// today — series, point queries, the table view, cardinality, PromQL series and
// the 1/sec cache-invalidation log query (a tag-only series query: empty `what`,
// group by tag1). what[] carries data_model.DigestSelector kinds; an empty
// what[] is legal and means "grouped tags and timestamps only". by[] carries
// grouped tag indices; format.ShardTagIndex (-3) is legal and is answered from
// shard_num, not from storage.
//
// Row limit semantics: the aggregator executes with LIMIT row_limit+1, because
// LIMIT N cannot distinguish "exactly N rows" from truncation. If the extra row
// appears the call FAILS with row_limit — a partial series result is never
// returned and never cached by the API.
type StatshouseStoreQuerySeriesBytes struct {
	FieldsMask uint32
	Base       StatshouseStoreQueryBaseBytes
	What       []int32
	By         []int32
	// MinHost (TrueType) // Conditional: item.FieldsMask.0
	// MaxHost (TrueType) // Conditional: item.FieldsMask.1
	// table view; absent = unsorted
	// SortDesc (TrueType) // Conditional: item.FieldsMask.2
	// SortAsc (TrueType) // Conditional: item.FieldsMask.3
}

func (StatshouseStoreQuerySeriesBytes) TLName() string { return "statshouse.storeQuerySeries" }
func (StatshouseStoreQuerySeriesBytes) TLTag() uint32  { return 0x57cb1008 }

func (item *StatshouseStoreQuerySeriesBytes) SetMinHost(v bool) {
	if v {
		item.FieldsMask |= 1 << 0
	} else {
		item.FieldsMask &^= 1 << 0
	}
}
func (item *StatshouseStoreQuerySeriesBytes) IsSetMinHost() bool { return item.FieldsMask&(1<<0) != 0 }

func (item *StatshouseStoreQuerySeriesBytes) SetMaxHost(v bool) {
	if v {
		item.FieldsMask |= 1 << 1
	} else {
		item.FieldsMask &^= 1 << 1
	}
}
func (item *StatshouseStoreQuerySeriesBytes) IsSetMaxHost() bool { return item.FieldsMask&(1<<1) != 0 }

func (item *StatshouseStoreQuerySeriesBytes) SetSortDesc(v bool) {
	if v {
		item.FieldsMask |= 1 << 2
	} else {
		item.FieldsMask &^= 1 << 2
	}
}
func (item *StatshouseStoreQuerySeriesBytes) IsSetSortDesc() bool { return item.FieldsMask&(1<<2) != 0 }

func (item *StatshouseStoreQuerySeriesBytes) SetSortAsc(v bool) {
	if v {
		item.FieldsMask |= 1 << 3
	} else {
		item.FieldsMask &^= 1 << 3
	}
}
func (item *StatshouseStoreQuerySeriesBytes) IsSetSortAsc() bool { return item.FieldsMask&(1<<3) != 0 }

func (item *StatshouseStoreQuerySeriesBytes) Reset() {
	item.FieldsMask = 0
	item.Base.Reset()
	item.What = item.What[:0]
	item.By = item.By[:0]
}

func (item *StatshouseStoreQuerySeriesBytes) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b1111)
	item.Base.FillRandom(rg)
	BuiltinVectorIntFillRandom(rg, &item.What)
	BuiltinVectorIntFillRandom(rg, &item.By)
}

func (item *StatshouseStoreQuerySeriesBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = item.Base.ReadTL1(w); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorIntReadTL1(w, &item.What); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorIntReadTL1(w, &item.By); err != nil {
		return w, err
	}
	return w, nil
}

func (item *StatshouseStoreQuerySeriesBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreQuerySeriesBytes) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Base.WriteTL1(w)
	w = BuiltinVectorIntWriteTL1(w, item.What)
	w = BuiltinVectorIntWriteTL1(w, item.By)
	return w
}

func (item *StatshouseStoreQuerySeriesBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1008); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreQuerySeriesBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreQuerySeriesBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1008)
	return item.WriteTL1(w)
}

func (item *StatshouseStoreQuerySeriesBytes) ReadResultTL1(w []byte, ret *StatshouseStoreSeriesResponseBytes) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseStoreQuerySeriesBytes) WriteResultTL1(w []byte, ret StatshouseStoreSeriesResponseBytes) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseStoreQuerySeriesBytes) ReadResultJSON(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, ret *StatshouseStoreSeriesResponseBytes) error {
	if err := ret.ReadJSONGeneral(jctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseStoreQuerySeriesBytes) WriteResultJSON(w []byte, ret StatshouseStoreSeriesResponseBytes) (_ []byte, err error) {
	return item.writeResultJSON(nil, w, ret)
}

func (item *StatshouseStoreQuerySeriesBytes) writeResultJSON(jctx *basictl.JSONWriteContext, w []byte, ret StatshouseStoreSeriesResponseBytes) (_ []byte, err error) {
	w = ret.WriteJSONOpt(jctx, w)
	return w, nil
}

func (item *StatshouseStoreQuerySeriesBytes) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret StatshouseStoreSeriesResponseBytes
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseStoreQuerySeriesBytes) ReadResultTL1WriteResultJSON(jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreSeriesResponseBytes
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(jctx, w, ret)
	return r, w, err
}

func (item *StatshouseStoreQuerySeriesBytes) ReadResultJSONWriteResultTL1(jctx *basictl.JSONReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreSeriesResponseBytes
	if err = item.ReadResultJSON(jctx, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseStoreQuerySeriesBytes) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries")
}

func (item *StatshouseStoreQuerySeriesBytes) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries")
}

func (item *StatshouseStoreQuerySeriesBytes) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries")
}

func (item *StatshouseStoreQuerySeriesBytes) ReadResultJSONWriteResultTL2(jctx *basictl.JSONReadContext, tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries")
}

func (item StatshouseStoreQuerySeriesBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreQuerySeriesBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreQuerySeriesBytes) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propBasePresented bool
	var propWhatPresented bool
	var propByPresented bool
	var propMinHostPresented bool
	var trueTypeMinHostValue bool
	var propMaxHostPresented bool
	var trueTypeMaxHostValue bool
	var propSortDescPresented bool
	var trueTypeSortDescValue bool
	var propSortAscPresented bool
	var trueTypeSortAscValue bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "base":
				if propBasePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "base")
				}
				propBasePresented = true
				if err := item.Base.ReadJSONGeneral(jctx, in); err != nil {
					return err
				}
			case "what":
				if propWhatPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "what")
				}
				propWhatPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.What); err != nil {
					return err
				}
			case "by":
				if propByPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "by")
				}
				propByPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.By); err != nil {
					return err
				}
			case "min_host":
				if propMinHostPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "min_host")
				}
				propMinHostPresented = true
				if err := Json2ReadBool(in, &trueTypeMinHostValue); err != nil {
					return err
				}
			case "max_host":
				if propMaxHostPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "max_host")
				}
				propMaxHostPresented = true
				if err := Json2ReadBool(in, &trueTypeMaxHostValue); err != nil {
					return err
				}
			case "sort_desc":
				if propSortDescPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "sort_desc")
				}
				propSortDescPresented = true
				if err := Json2ReadBool(in, &trueTypeSortDescValue); err != nil {
					return err
				}
			case "sort_asc":
				if propSortAscPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQuerySeries", "sort_asc")
				}
				propSortAscPresented = true
				if err := Json2ReadBool(in, &trueTypeSortAscValue); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeQuerySeries", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propBasePresented {
		item.Base.Reset()
	}
	if !propWhatPresented {
		item.What = item.What[:0]
	}
	if !propByPresented {
		item.By = item.By[:0]
	}
	if trueTypeMinHostValue {
		item.FieldsMask |= 1 << 0
	}
	if trueTypeMaxHostValue {
		item.FieldsMask |= 1 << 1
	}
	if trueTypeSortDescValue {
		item.FieldsMask |= 1 << 2
	}
	if trueTypeSortAscValue {
		item.FieldsMask |= 1 << 3
	}
	if propMinHostPresented && !trueTypeMinHostValue && (item.FieldsMask&(1<<0) != 0) {
		return ErrorInvalidJSON("statshouse.storeQuerySeries", "field 'min_host' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 0 is 1")
	}
	if propMaxHostPresented && !trueTypeMaxHostValue && (item.FieldsMask&(1<<1) != 0) {
		return ErrorInvalidJSON("statshouse.storeQuerySeries", "field 'max_host' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 1 is 1")
	}
	if propSortDescPresented && !trueTypeSortDescValue && (item.FieldsMask&(1<<2) != 0) {
		return ErrorInvalidJSON("statshouse.storeQuerySeries", "field 'sort_desc' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 2 is 1")
	}
	if propSortAscPresented && !trueTypeSortAscValue && (item.FieldsMask&(1<<3) != 0) {
		return ErrorInvalidJSON("statshouse.storeQuerySeries", "field 'sort_asc' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 3 is 1")
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreQuerySeriesBytes) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreQuerySeriesBytes) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreQuerySeriesBytes) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"base":`...)
	w = item.Base.WriteJSONOpt(jctx, w)
	backupIndexWhat := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"what":`...)
	w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.What)
	if !(len(item.What) != 0) {
		w = w[:backupIndexWhat]
	}
	backupIndexBy := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"by":`...)
	w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.By)
	if !(len(item.By) != 0) {
		w = w[:backupIndexBy]
	}
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"min_host":true`...)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"max_host":true`...)
	}
	if item.FieldsMask&(1<<2) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"sort_desc":true`...)
	}
	if item.FieldsMask&(1<<3) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"sort_asc":true`...)
	}
	return append(w, '}')
}

func (item *StatshouseStoreQuerySeriesBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreQuerySeriesBytes) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeQuerySeries", err.Error())
	}
	return nil
}

func (item *StatshouseStoreQuerySeriesBytes) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries"))
}

func (item *StatshouseStoreQuerySeriesBytes) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeQuerySeries")
}
