// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

// Shared by both query verbs.
type StatshouseStoreQueryBase struct {
	FieldsMask uint32
	MetricId   int32
	// journal version tag_layout was read at
	MetricVersion int64
	TagLayout     StatshouseStoreTagLayout
	// multi-metric filter (PromQL)
	MetricIn    []int32 // Conditional: item.FieldsMask.0
	MetricNotIn []int32 // Conditional: item.FieldsMask.1
	Lod         StatshouseStoreLod
	FilterIn    []StatshouseStoreTagFilter
	FilterNotIn []StatshouseStoreTagFilter
	// clamped by the aggregator to its own max
	RowLimit int32
	// RELATIVE, not an absolute deadline: immune to clock skew
	TimeoutMs int32
}

func (StatshouseStoreQueryBase) TLName() string { return "statshouse.storeQueryBase" }
func (StatshouseStoreQueryBase) TLTag() uint32  { return 0x57cb1004 }

func (item *StatshouseStoreQueryBase) SetMetricIn(v []int32) {
	item.MetricIn = v
	item.FieldsMask |= 1 << 0
}
func (item *StatshouseStoreQueryBase) ClearMetricIn() {
	item.MetricIn = item.MetricIn[:0]
	item.FieldsMask &^= 1 << 0
}
func (item *StatshouseStoreQueryBase) IsSetMetricIn() bool { return item.FieldsMask&(1<<0) != 0 }

func (item *StatshouseStoreQueryBase) SetMetricNotIn(v []int32) {
	item.MetricNotIn = v
	item.FieldsMask |= 1 << 1
}
func (item *StatshouseStoreQueryBase) ClearMetricNotIn() {
	item.MetricNotIn = item.MetricNotIn[:0]
	item.FieldsMask &^= 1 << 1
}
func (item *StatshouseStoreQueryBase) IsSetMetricNotIn() bool { return item.FieldsMask&(1<<1) != 0 }

func (item *StatshouseStoreQueryBase) Reset() {
	item.FieldsMask = 0
	item.MetricId = 0
	item.MetricVersion = 0
	item.TagLayout.Reset()
	item.MetricIn = item.MetricIn[:0]
	item.MetricNotIn = item.MetricNotIn[:0]
	item.Lod.Reset()
	item.FilterIn = item.FilterIn[:0]
	item.FilterNotIn = item.FilterNotIn[:0]
	item.RowLimit = 0
	item.TimeoutMs = 0
}

func (item *StatshouseStoreQueryBase) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b11)
	item.MetricId = basictl.RandomInt(rg)
	item.MetricVersion = basictl.RandomLong(rg)
	item.TagLayout.FillRandom(rg)
	if item.FieldsMask&(1<<0) != 0 {
		BuiltinVectorIntFillRandom(rg, &item.MetricIn)
	} else {
		item.MetricIn = item.MetricIn[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		BuiltinVectorIntFillRandom(rg, &item.MetricNotIn)
	} else {
		item.MetricNotIn = item.MetricNotIn[:0]
	}
	item.Lod.FillRandom(rg)
	BuiltinVectorStatshouseStoreTagFilterBoxedFillRandom(rg, &item.FilterIn)
	BuiltinVectorStatshouseStoreTagFilterBoxedFillRandom(rg, &item.FilterNotIn)
	item.RowLimit = basictl.RandomInt(rg)
	item.TimeoutMs = basictl.RandomInt(rg)
}

func (item *StatshouseStoreQueryBase) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.MetricId); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.MetricVersion); err != nil {
		return w, err
	}
	if w, err = item.TagLayout.ReadTL1Boxed(w); err != nil {
		return w, err
	}
	if item.FieldsMask&(1<<0) != 0 {
		if w, err = BuiltinVectorIntReadTL1(w, &item.MetricIn); err != nil {
			return w, err
		}
	} else {
		item.MetricIn = item.MetricIn[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		if w, err = BuiltinVectorIntReadTL1(w, &item.MetricNotIn); err != nil {
			return w, err
		}
	} else {
		item.MetricNotIn = item.MetricNotIn[:0]
	}
	if w, err = item.Lod.ReadTL1Boxed(w); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorStatshouseStoreTagFilterBoxedReadTL1(w, &item.FilterIn); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorStatshouseStoreTagFilterBoxedReadTL1(w, &item.FilterNotIn); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.RowLimit); err != nil {
		return w, err
	}
	return basictl.IntRead(w, &item.TimeoutMs)
}

func (item *StatshouseStoreQueryBase) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreQueryBase) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = basictl.IntWrite(w, item.MetricId)
	w = basictl.LongWrite(w, item.MetricVersion)
	w = item.TagLayout.WriteTL1Boxed(w)
	if item.FieldsMask&(1<<0) != 0 {
		w = BuiltinVectorIntWriteTL1(w, item.MetricIn)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = BuiltinVectorIntWriteTL1(w, item.MetricNotIn)
	}
	w = item.Lod.WriteTL1Boxed(w)
	w = BuiltinVectorStatshouseStoreTagFilterBoxedWriteTL1(w, item.FilterIn)
	w = BuiltinVectorStatshouseStoreTagFilterBoxedWriteTL1(w, item.FilterNotIn)
	w = basictl.IntWrite(w, item.RowLimit)
	w = basictl.IntWrite(w, item.TimeoutMs)
	return w
}

func (item *StatshouseStoreQueryBase) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1004); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreQueryBase) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreQueryBase) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1004)
	return item.WriteTL1(w)
}

func (item StatshouseStoreQueryBase) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreQueryBase) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreQueryBase) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propMetricIdPresented bool
	var propMetricVersionPresented bool
	var propTagLayoutPresented bool
	var propMetricInPresented bool
	var propMetricNotInPresented bool
	var propLodPresented bool
	var propFilterInPresented bool
	var propFilterNotInPresented bool
	var propRowLimitPresented bool
	var propTimeoutMsPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "metric_id":
				if propMetricIdPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "metric_id")
				}
				propMetricIdPresented = true
				if err := Json2ReadInt32(in, &item.MetricId); err != nil {
					return err
				}
			case "metric_version":
				if propMetricVersionPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "metric_version")
				}
				propMetricVersionPresented = true
				if err := Json2ReadInt64(in, &item.MetricVersion); err != nil {
					return err
				}
			case "tag_layout":
				if propTagLayoutPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "tag_layout")
				}
				propTagLayoutPresented = true
				if err := item.TagLayout.ReadJSONGeneral(jctx, in); err != nil {
					return err
				}
			case "metric_in":
				if propMetricInPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "metric_in")
				}
				propMetricInPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.MetricIn); err != nil {
					return err
				}
			case "metric_not_in":
				if propMetricNotInPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "metric_not_in")
				}
				propMetricNotInPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.MetricNotIn); err != nil {
					return err
				}
			case "lod":
				if propLodPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "lod")
				}
				propLodPresented = true
				if err := item.Lod.ReadJSONGeneral(jctx, in); err != nil {
					return err
				}
			case "filter_in":
				if propFilterInPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "filter_in")
				}
				propFilterInPresented = true
				if err := BuiltinVectorStatshouseStoreTagFilterBoxedReadJSONGeneral(jctx, in, &item.FilterIn); err != nil {
					return err
				}
			case "filter_not_in":
				if propFilterNotInPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "filter_not_in")
				}
				propFilterNotInPresented = true
				if err := BuiltinVectorStatshouseStoreTagFilterBoxedReadJSONGeneral(jctx, in, &item.FilterNotIn); err != nil {
					return err
				}
			case "row_limit":
				if propRowLimitPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "row_limit")
				}
				propRowLimitPresented = true
				if err := Json2ReadInt32(in, &item.RowLimit); err != nil {
					return err
				}
			case "timeout_ms":
				if propTimeoutMsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "timeout_ms")
				}
				propTimeoutMsPresented = true
				if err := Json2ReadInt32(in, &item.TimeoutMs); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeQueryBase", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propMetricIdPresented {
		item.MetricId = 0
	}
	if !propMetricVersionPresented {
		item.MetricVersion = 0
	}
	if !propTagLayoutPresented {
		item.TagLayout.Reset()
	}
	if !propMetricInPresented {
		item.MetricIn = item.MetricIn[:0]
	}
	if !propMetricNotInPresented {
		item.MetricNotIn = item.MetricNotIn[:0]
	}
	if !propLodPresented {
		item.Lod.Reset()
	}
	if !propFilterInPresented {
		item.FilterIn = item.FilterIn[:0]
	}
	if !propFilterNotInPresented {
		item.FilterNotIn = item.FilterNotIn[:0]
	}
	if !propRowLimitPresented {
		item.RowLimit = 0
	}
	if !propTimeoutMsPresented {
		item.TimeoutMs = 0
	}
	if propMetricInPresented {
		item.FieldsMask |= 1 << 0
	}
	if propMetricNotInPresented {
		item.FieldsMask |= 1 << 1
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreQueryBase) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreQueryBase) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreQueryBase) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexMetricId := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"metric_id":`...)
	w = basictl.JSONWriteInt32(w, item.MetricId)
	if !(item.MetricId != 0) {
		w = w[:backupIndexMetricId]
	}
	backupIndexMetricVersion := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"metric_version":`...)
	w = basictl.JSONWriteInt64(w, item.MetricVersion)
	if !(item.MetricVersion != 0) {
		w = w[:backupIndexMetricVersion]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"tag_layout":`...)
	w = item.TagLayout.WriteJSONOpt(jctx, w)
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"metric_in":`...)
		w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.MetricIn)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"metric_not_in":`...)
		w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.MetricNotIn)
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"lod":`...)
	w = item.Lod.WriteJSONOpt(jctx, w)
	backupIndexFilterIn := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"filter_in":`...)
	w = BuiltinVectorStatshouseStoreTagFilterBoxedWriteJSONOpt(jctx, w, item.FilterIn)
	if !(len(item.FilterIn) != 0) {
		w = w[:backupIndexFilterIn]
	}
	backupIndexFilterNotIn := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"filter_not_in":`...)
	w = BuiltinVectorStatshouseStoreTagFilterBoxedWriteJSONOpt(jctx, w, item.FilterNotIn)
	if !(len(item.FilterNotIn) != 0) {
		w = w[:backupIndexFilterNotIn]
	}
	backupIndexRowLimit := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"row_limit":`...)
	w = basictl.JSONWriteInt32(w, item.RowLimit)
	if !(item.RowLimit != 0) {
		w = w[:backupIndexRowLimit]
	}
	backupIndexTimeoutMs := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"timeout_ms":`...)
	w = basictl.JSONWriteInt32(w, item.TimeoutMs)
	if !(item.TimeoutMs != 0) {
		w = w[:backupIndexTimeoutMs]
	}
	return append(w, '}')
}

func (item *StatshouseStoreQueryBase) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreQueryBase) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeQueryBase", err.Error())
	}
	return nil
}

func (item *StatshouseStoreQueryBase) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeQueryBase"))
}

func (item *StatshouseStoreQueryBase) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeQueryBase")
}

// Shared by both query verbs.
type StatshouseStoreQueryBaseBytes struct {
	FieldsMask uint32
	MetricId   int32
	// journal version tag_layout was read at
	MetricVersion int64
	TagLayout     StatshouseStoreTagLayout
	// multi-metric filter (PromQL)
	MetricIn    []int32 // Conditional: item.FieldsMask.0
	MetricNotIn []int32 // Conditional: item.FieldsMask.1
	Lod         StatshouseStoreLodBytes
	FilterIn    []StatshouseStoreTagFilterBytes
	FilterNotIn []StatshouseStoreTagFilterBytes
	// clamped by the aggregator to its own max
	RowLimit int32
	// RELATIVE, not an absolute deadline: immune to clock skew
	TimeoutMs int32
}

func (StatshouseStoreQueryBaseBytes) TLName() string { return "statshouse.storeQueryBase" }
func (StatshouseStoreQueryBaseBytes) TLTag() uint32  { return 0x57cb1004 }

func (item *StatshouseStoreQueryBaseBytes) SetMetricIn(v []int32) {
	item.MetricIn = v
	item.FieldsMask |= 1 << 0
}
func (item *StatshouseStoreQueryBaseBytes) ClearMetricIn() {
	item.MetricIn = item.MetricIn[:0]
	item.FieldsMask &^= 1 << 0
}
func (item *StatshouseStoreQueryBaseBytes) IsSetMetricIn() bool { return item.FieldsMask&(1<<0) != 0 }

func (item *StatshouseStoreQueryBaseBytes) SetMetricNotIn(v []int32) {
	item.MetricNotIn = v
	item.FieldsMask |= 1 << 1
}
func (item *StatshouseStoreQueryBaseBytes) ClearMetricNotIn() {
	item.MetricNotIn = item.MetricNotIn[:0]
	item.FieldsMask &^= 1 << 1
}
func (item *StatshouseStoreQueryBaseBytes) IsSetMetricNotIn() bool {
	return item.FieldsMask&(1<<1) != 0
}

func (item *StatshouseStoreQueryBaseBytes) Reset() {
	item.FieldsMask = 0
	item.MetricId = 0
	item.MetricVersion = 0
	item.TagLayout.Reset()
	item.MetricIn = item.MetricIn[:0]
	item.MetricNotIn = item.MetricNotIn[:0]
	item.Lod.Reset()
	item.FilterIn = item.FilterIn[:0]
	item.FilterNotIn = item.FilterNotIn[:0]
	item.RowLimit = 0
	item.TimeoutMs = 0
}

func (item *StatshouseStoreQueryBaseBytes) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b11)
	item.MetricId = basictl.RandomInt(rg)
	item.MetricVersion = basictl.RandomLong(rg)
	item.TagLayout.FillRandom(rg)
	if item.FieldsMask&(1<<0) != 0 {
		BuiltinVectorIntFillRandom(rg, &item.MetricIn)
	} else {
		item.MetricIn = item.MetricIn[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		BuiltinVectorIntFillRandom(rg, &item.MetricNotIn)
	} else {
		item.MetricNotIn = item.MetricNotIn[:0]
	}
	item.Lod.FillRandom(rg)
	BuiltinVectorStatshouseStoreTagFilterBoxedBytesFillRandom(rg, &item.FilterIn)
	BuiltinVectorStatshouseStoreTagFilterBoxedBytesFillRandom(rg, &item.FilterNotIn)
	item.RowLimit = basictl.RandomInt(rg)
	item.TimeoutMs = basictl.RandomInt(rg)
}

func (item *StatshouseStoreQueryBaseBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.MetricId); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.MetricVersion); err != nil {
		return w, err
	}
	if w, err = item.TagLayout.ReadTL1Boxed(w); err != nil {
		return w, err
	}
	if item.FieldsMask&(1<<0) != 0 {
		if w, err = BuiltinVectorIntReadTL1(w, &item.MetricIn); err != nil {
			return w, err
		}
	} else {
		item.MetricIn = item.MetricIn[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		if w, err = BuiltinVectorIntReadTL1(w, &item.MetricNotIn); err != nil {
			return w, err
		}
	} else {
		item.MetricNotIn = item.MetricNotIn[:0]
	}
	if w, err = item.Lod.ReadTL1Boxed(w); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorStatshouseStoreTagFilterBoxedBytesReadTL1(w, &item.FilterIn); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorStatshouseStoreTagFilterBoxedBytesReadTL1(w, &item.FilterNotIn); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.RowLimit); err != nil {
		return w, err
	}
	return basictl.IntRead(w, &item.TimeoutMs)
}

func (item *StatshouseStoreQueryBaseBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreQueryBaseBytes) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = basictl.IntWrite(w, item.MetricId)
	w = basictl.LongWrite(w, item.MetricVersion)
	w = item.TagLayout.WriteTL1Boxed(w)
	if item.FieldsMask&(1<<0) != 0 {
		w = BuiltinVectorIntWriteTL1(w, item.MetricIn)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = BuiltinVectorIntWriteTL1(w, item.MetricNotIn)
	}
	w = item.Lod.WriteTL1Boxed(w)
	w = BuiltinVectorStatshouseStoreTagFilterBoxedBytesWriteTL1(w, item.FilterIn)
	w = BuiltinVectorStatshouseStoreTagFilterBoxedBytesWriteTL1(w, item.FilterNotIn)
	w = basictl.IntWrite(w, item.RowLimit)
	w = basictl.IntWrite(w, item.TimeoutMs)
	return w
}

func (item *StatshouseStoreQueryBaseBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1004); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreQueryBaseBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreQueryBaseBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1004)
	return item.WriteTL1(w)
}

func (item StatshouseStoreQueryBaseBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreQueryBaseBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreQueryBaseBytes) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propMetricIdPresented bool
	var propMetricVersionPresented bool
	var propTagLayoutPresented bool
	var propMetricInPresented bool
	var propMetricNotInPresented bool
	var propLodPresented bool
	var propFilterInPresented bool
	var propFilterNotInPresented bool
	var propRowLimitPresented bool
	var propTimeoutMsPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "metric_id":
				if propMetricIdPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "metric_id")
				}
				propMetricIdPresented = true
				if err := Json2ReadInt32(in, &item.MetricId); err != nil {
					return err
				}
			case "metric_version":
				if propMetricVersionPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "metric_version")
				}
				propMetricVersionPresented = true
				if err := Json2ReadInt64(in, &item.MetricVersion); err != nil {
					return err
				}
			case "tag_layout":
				if propTagLayoutPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "tag_layout")
				}
				propTagLayoutPresented = true
				if err := item.TagLayout.ReadJSONGeneral(jctx, in); err != nil {
					return err
				}
			case "metric_in":
				if propMetricInPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "metric_in")
				}
				propMetricInPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.MetricIn); err != nil {
					return err
				}
			case "metric_not_in":
				if propMetricNotInPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "metric_not_in")
				}
				propMetricNotInPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.MetricNotIn); err != nil {
					return err
				}
			case "lod":
				if propLodPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "lod")
				}
				propLodPresented = true
				if err := item.Lod.ReadJSONGeneral(jctx, in); err != nil {
					return err
				}
			case "filter_in":
				if propFilterInPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "filter_in")
				}
				propFilterInPresented = true
				if err := BuiltinVectorStatshouseStoreTagFilterBoxedBytesReadJSONGeneral(jctx, in, &item.FilterIn); err != nil {
					return err
				}
			case "filter_not_in":
				if propFilterNotInPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "filter_not_in")
				}
				propFilterNotInPresented = true
				if err := BuiltinVectorStatshouseStoreTagFilterBoxedBytesReadJSONGeneral(jctx, in, &item.FilterNotIn); err != nil {
					return err
				}
			case "row_limit":
				if propRowLimitPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "row_limit")
				}
				propRowLimitPresented = true
				if err := Json2ReadInt32(in, &item.RowLimit); err != nil {
					return err
				}
			case "timeout_ms":
				if propTimeoutMsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryBase", "timeout_ms")
				}
				propTimeoutMsPresented = true
				if err := Json2ReadInt32(in, &item.TimeoutMs); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeQueryBase", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propMetricIdPresented {
		item.MetricId = 0
	}
	if !propMetricVersionPresented {
		item.MetricVersion = 0
	}
	if !propTagLayoutPresented {
		item.TagLayout.Reset()
	}
	if !propMetricInPresented {
		item.MetricIn = item.MetricIn[:0]
	}
	if !propMetricNotInPresented {
		item.MetricNotIn = item.MetricNotIn[:0]
	}
	if !propLodPresented {
		item.Lod.Reset()
	}
	if !propFilterInPresented {
		item.FilterIn = item.FilterIn[:0]
	}
	if !propFilterNotInPresented {
		item.FilterNotIn = item.FilterNotIn[:0]
	}
	if !propRowLimitPresented {
		item.RowLimit = 0
	}
	if !propTimeoutMsPresented {
		item.TimeoutMs = 0
	}
	if propMetricInPresented {
		item.FieldsMask |= 1 << 0
	}
	if propMetricNotInPresented {
		item.FieldsMask |= 1 << 1
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreQueryBaseBytes) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreQueryBaseBytes) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreQueryBaseBytes) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexMetricId := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"metric_id":`...)
	w = basictl.JSONWriteInt32(w, item.MetricId)
	if !(item.MetricId != 0) {
		w = w[:backupIndexMetricId]
	}
	backupIndexMetricVersion := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"metric_version":`...)
	w = basictl.JSONWriteInt64(w, item.MetricVersion)
	if !(item.MetricVersion != 0) {
		w = w[:backupIndexMetricVersion]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"tag_layout":`...)
	w = item.TagLayout.WriteJSONOpt(jctx, w)
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"metric_in":`...)
		w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.MetricIn)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"metric_not_in":`...)
		w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.MetricNotIn)
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"lod":`...)
	w = item.Lod.WriteJSONOpt(jctx, w)
	backupIndexFilterIn := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"filter_in":`...)
	w = BuiltinVectorStatshouseStoreTagFilterBoxedBytesWriteJSONOpt(jctx, w, item.FilterIn)
	if !(len(item.FilterIn) != 0) {
		w = w[:backupIndexFilterIn]
	}
	backupIndexFilterNotIn := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"filter_not_in":`...)
	w = BuiltinVectorStatshouseStoreTagFilterBoxedBytesWriteJSONOpt(jctx, w, item.FilterNotIn)
	if !(len(item.FilterNotIn) != 0) {
		w = w[:backupIndexFilterNotIn]
	}
	backupIndexRowLimit := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"row_limit":`...)
	w = basictl.JSONWriteInt32(w, item.RowLimit)
	if !(item.RowLimit != 0) {
		w = w[:backupIndexRowLimit]
	}
	backupIndexTimeoutMs := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"timeout_ms":`...)
	w = basictl.JSONWriteInt32(w, item.TimeoutMs)
	if !(item.TimeoutMs != 0) {
		w = w[:backupIndexTimeoutMs]
	}
	return append(w, '}')
}

func (item *StatshouseStoreQueryBaseBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreQueryBaseBytes) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeQueryBase", err.Error())
	}
	return nil
}

func (item *StatshouseStoreQueryBaseBytes) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeQueryBase"))
}

func (item *StatshouseStoreQueryBaseBytes) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeQueryBase")
}
