// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type StatshouseStoreSeriesResponse struct {
	FieldsMask uint32
	// the aggregator's own shard, supplied as a literal: nothing is stored per-row
	ShardNum int32
	Batches  []StatshouseStoreSeriesBatch
}

func (StatshouseStoreSeriesResponse) TLName() string { return "statshouse.storeSeriesResponse" }
func (StatshouseStoreSeriesResponse) TLTag() uint32  { return 0x57cb1006 }

func (item *StatshouseStoreSeriesResponse) Reset() {
	item.FieldsMask = 0
	item.ShardNum = 0
	item.Batches = item.Batches[:0]
}

func (item *StatshouseStoreSeriesResponse) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomUint(rg)
	item.ShardNum = basictl.RandomInt(rg)
	BuiltinVectorStatshouseStoreSeriesBatchBoxedFillRandom(rg, &item.Batches)
}

func (item *StatshouseStoreSeriesResponse) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.ShardNum); err != nil {
		return w, err
	}
	return BuiltinVectorStatshouseStoreSeriesBatchBoxedReadTL1(w, &item.Batches)
}

func (item *StatshouseStoreSeriesResponse) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreSeriesResponse) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = basictl.IntWrite(w, item.ShardNum)
	w = BuiltinVectorStatshouseStoreSeriesBatchBoxedWriteTL1(w, item.Batches)
	return w
}

func (item *StatshouseStoreSeriesResponse) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1006); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreSeriesResponse) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreSeriesResponse) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1006)
	return item.WriteTL1(w)
}

func (item StatshouseStoreSeriesResponse) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreSeriesResponse) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreSeriesResponse) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propShardNumPresented bool
	var propBatchesPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesResponse", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "shard_num":
				if propShardNumPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesResponse", "shard_num")
				}
				propShardNumPresented = true
				if err := Json2ReadInt32(in, &item.ShardNum); err != nil {
					return err
				}
			case "batches":
				if propBatchesPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesResponse", "batches")
				}
				propBatchesPresented = true
				if err := BuiltinVectorStatshouseStoreSeriesBatchBoxedReadJSONGeneral(jctx, in, &item.Batches); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeSeriesResponse", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propShardNumPresented {
		item.ShardNum = 0
	}
	if !propBatchesPresented {
		item.Batches = item.Batches[:0]
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreSeriesResponse) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreSeriesResponse) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreSeriesResponse) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexShardNum := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"shard_num":`...)
	w = basictl.JSONWriteInt32(w, item.ShardNum)
	if !(item.ShardNum != 0) {
		w = w[:backupIndexShardNum]
	}
	backupIndexBatches := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"batches":`...)
	w = BuiltinVectorStatshouseStoreSeriesBatchBoxedWriteJSONOpt(jctx, w, item.Batches)
	if !(len(item.Batches) != 0) {
		w = w[:backupIndexBatches]
	}
	return append(w, '}')
}

func (item *StatshouseStoreSeriesResponse) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreSeriesResponse) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeSeriesResponse", err.Error())
	}
	return nil
}

func (item *StatshouseStoreSeriesResponse) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeSeriesResponse"))
}

func (item *StatshouseStoreSeriesResponse) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeSeriesResponse")
}

type StatshouseStoreSeriesResponseBytes struct {
	FieldsMask uint32
	// the aggregator's own shard, supplied as a literal: nothing is stored per-row
	ShardNum int32
	Batches  []StatshouseStoreSeriesBatchBytes
}

func (StatshouseStoreSeriesResponseBytes) TLName() string { return "statshouse.storeSeriesResponse" }
func (StatshouseStoreSeriesResponseBytes) TLTag() uint32  { return 0x57cb1006 }

func (item *StatshouseStoreSeriesResponseBytes) Reset() {
	item.FieldsMask = 0
	item.ShardNum = 0
	item.Batches = item.Batches[:0]
}

func (item *StatshouseStoreSeriesResponseBytes) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomUint(rg)
	item.ShardNum = basictl.RandomInt(rg)
	BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesFillRandom(rg, &item.Batches)
}

func (item *StatshouseStoreSeriesResponseBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.ShardNum); err != nil {
		return w, err
	}
	return BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesReadTL1(w, &item.Batches)
}

func (item *StatshouseStoreSeriesResponseBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreSeriesResponseBytes) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = basictl.IntWrite(w, item.ShardNum)
	w = BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesWriteTL1(w, item.Batches)
	return w
}

func (item *StatshouseStoreSeriesResponseBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1006); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreSeriesResponseBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreSeriesResponseBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1006)
	return item.WriteTL1(w)
}

func (item StatshouseStoreSeriesResponseBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreSeriesResponseBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreSeriesResponseBytes) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propShardNumPresented bool
	var propBatchesPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesResponse", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "shard_num":
				if propShardNumPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesResponse", "shard_num")
				}
				propShardNumPresented = true
				if err := Json2ReadInt32(in, &item.ShardNum); err != nil {
					return err
				}
			case "batches":
				if propBatchesPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesResponse", "batches")
				}
				propBatchesPresented = true
				if err := BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesReadJSONGeneral(jctx, in, &item.Batches); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeSeriesResponse", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propShardNumPresented {
		item.ShardNum = 0
	}
	if !propBatchesPresented {
		item.Batches = item.Batches[:0]
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreSeriesResponseBytes) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreSeriesResponseBytes) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreSeriesResponseBytes) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexShardNum := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"shard_num":`...)
	w = basictl.JSONWriteInt32(w, item.ShardNum)
	if !(item.ShardNum != 0) {
		w = w[:backupIndexShardNum]
	}
	backupIndexBatches := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"batches":`...)
	w = BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesWriteJSONOpt(jctx, w, item.Batches)
	if !(len(item.Batches) != 0) {
		w = w[:backupIndexBatches]
	}
	return append(w, '}')
}

func (item *StatshouseStoreSeriesResponseBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreSeriesResponseBytes) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeSeriesResponse", err.Error())
	}
	return nil
}

func (item *StatshouseStoreSeriesResponseBytes) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeSeriesResponse"))
}

func (item *StatshouseStoreSeriesResponseBytes) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeSeriesResponse")
}
