// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

// The queried resolution window. step_sec is one of the 11 LOD steps; the
// aggregator maps it onto the 1s/1m/1h tier table itself. location is only
// meaningful for the _1M (calendar month) step; every other step uses utc_offset.
type StatshouseStoreLod struct {
	// inclusive
	FromSec int64
	// exclusive
	ToSec     int64
	StepSec   int64
	UtcOffset int64
	// IANA name, e.g. "Europe/Moscow"
	Location string
}

func (StatshouseStoreLod) TLName() string { return "statshouse.storeLod" }
func (StatshouseStoreLod) TLTag() uint32  { return 0x57cb1003 }

func (item *StatshouseStoreLod) Reset() {
	item.FromSec = 0
	item.ToSec = 0
	item.StepSec = 0
	item.UtcOffset = 0
	item.Location = ""
}

func (item *StatshouseStoreLod) FillRandom(rg *basictl.RandGenerator) {
	item.FromSec = basictl.RandomLong(rg)
	item.ToSec = basictl.RandomLong(rg)
	item.StepSec = basictl.RandomLong(rg)
	item.UtcOffset = basictl.RandomLong(rg)
	item.Location = basictl.RandomString(rg)
}

func (item *StatshouseStoreLod) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.LongRead(w, &item.FromSec); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.ToSec); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.StepSec); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.UtcOffset); err != nil {
		return w, err
	}
	return basictl.StringRead(w, &item.Location)
}

func (item *StatshouseStoreLod) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreLod) WriteTL1(w []byte) []byte {
	w = basictl.LongWrite(w, item.FromSec)
	w = basictl.LongWrite(w, item.ToSec)
	w = basictl.LongWrite(w, item.StepSec)
	w = basictl.LongWrite(w, item.UtcOffset)
	w = basictl.StringWrite(w, item.Location)
	return w
}

func (item *StatshouseStoreLod) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1003); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreLod) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreLod) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1003)
	return item.WriteTL1(w)
}

func (item StatshouseStoreLod) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreLod) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreLod) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFromSecPresented bool
	var propToSecPresented bool
	var propStepSecPresented bool
	var propUtcOffsetPresented bool
	var propLocationPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "from_sec":
				if propFromSecPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeLod", "from_sec")
				}
				propFromSecPresented = true
				if err := Json2ReadInt64(in, &item.FromSec); err != nil {
					return err
				}
			case "to_sec":
				if propToSecPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeLod", "to_sec")
				}
				propToSecPresented = true
				if err := Json2ReadInt64(in, &item.ToSec); err != nil {
					return err
				}
			case "step_sec":
				if propStepSecPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeLod", "step_sec")
				}
				propStepSecPresented = true
				if err := Json2ReadInt64(in, &item.StepSec); err != nil {
					return err
				}
			case "utc_offset":
				if propUtcOffsetPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeLod", "utc_offset")
				}
				propUtcOffsetPresented = true
				if err := Json2ReadInt64(in, &item.UtcOffset); err != nil {
					return err
				}
			case "location":
				if propLocationPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeLod", "location")
				}
				propLocationPresented = true
				if err := Json2ReadString(in, &item.Location); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeLod", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFromSecPresented {
		item.FromSec = 0
	}
	if !propToSecPresented {
		item.ToSec = 0
	}
	if !propStepSecPresented {
		item.StepSec = 0
	}
	if !propUtcOffsetPresented {
		item.UtcOffset = 0
	}
	if !propLocationPresented {
		item.Location = ""
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreLod) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreLod) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreLod) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFromSec := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"from_sec":`...)
	w = basictl.JSONWriteInt64(w, item.FromSec)
	if !(item.FromSec != 0) {
		w = w[:backupIndexFromSec]
	}
	backupIndexToSec := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"to_sec":`...)
	w = basictl.JSONWriteInt64(w, item.ToSec)
	if !(item.ToSec != 0) {
		w = w[:backupIndexToSec]
	}
	backupIndexStepSec := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"step_sec":`...)
	w = basictl.JSONWriteInt64(w, item.StepSec)
	if !(item.StepSec != 0) {
		w = w[:backupIndexStepSec]
	}
	backupIndexUtcOffset := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"utc_offset":`...)
	w = basictl.JSONWriteInt64(w, item.UtcOffset)
	if !(item.UtcOffset != 0) {
		w = w[:backupIndexUtcOffset]
	}
	backupIndexLocation := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"location":`...)
	w = basictl.JSONWriteString(w, item.Location)
	if !(len(item.Location) != 0) {
		w = w[:backupIndexLocation]
	}
	return append(w, '}')
}

func (item *StatshouseStoreLod) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreLod) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeLod", err.Error())
	}
	return nil
}

func (item *StatshouseStoreLod) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeLod"))
}

func (item *StatshouseStoreLod) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeLod")
}

// The queried resolution window. step_sec is one of the 11 LOD steps; the
// aggregator maps it onto the 1s/1m/1h tier table itself. location is only
// meaningful for the _1M (calendar month) step; every other step uses utc_offset.
type StatshouseStoreLodBytes struct {
	// inclusive
	FromSec int64
	// exclusive
	ToSec     int64
	StepSec   int64
	UtcOffset int64
	// IANA name, e.g. "Europe/Moscow"
	Location []byte
}

func (StatshouseStoreLodBytes) TLName() string { return "statshouse.storeLod" }
func (StatshouseStoreLodBytes) TLTag() uint32  { return 0x57cb1003 }

func (item *StatshouseStoreLodBytes) Reset() {
	item.FromSec = 0
	item.ToSec = 0
	item.StepSec = 0
	item.UtcOffset = 0
	item.Location = item.Location[:0]
}

func (item *StatshouseStoreLodBytes) FillRandom(rg *basictl.RandGenerator) {
	item.FromSec = basictl.RandomLong(rg)
	item.ToSec = basictl.RandomLong(rg)
	item.StepSec = basictl.RandomLong(rg)
	item.UtcOffset = basictl.RandomLong(rg)
	item.Location = basictl.RandomStringBytes(rg)
}

func (item *StatshouseStoreLodBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.LongRead(w, &item.FromSec); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.ToSec); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.StepSec); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.UtcOffset); err != nil {
		return w, err
	}
	return basictl.StringReadBytes(w, &item.Location)
}

func (item *StatshouseStoreLodBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreLodBytes) WriteTL1(w []byte) []byte {
	w = basictl.LongWrite(w, item.FromSec)
	w = basictl.LongWrite(w, item.ToSec)
	w = basictl.LongWrite(w, item.StepSec)
	w = basictl.LongWrite(w, item.UtcOffset)
	w = basictl.StringWriteBytes(w, item.Location)
	return w
}

func (item *StatshouseStoreLodBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1003); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreLodBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreLodBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1003)
	return item.WriteTL1(w)
}

func (item StatshouseStoreLodBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreLodBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreLodBytes) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFromSecPresented bool
	var propToSecPresented bool
	var propStepSecPresented bool
	var propUtcOffsetPresented bool
	var propLocationPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "from_sec":
				if propFromSecPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeLod", "from_sec")
				}
				propFromSecPresented = true
				if err := Json2ReadInt64(in, &item.FromSec); err != nil {
					return err
				}
			case "to_sec":
				if propToSecPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeLod", "to_sec")
				}
				propToSecPresented = true
				if err := Json2ReadInt64(in, &item.ToSec); err != nil {
					return err
				}
			case "step_sec":
				if propStepSecPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeLod", "step_sec")
				}
				propStepSecPresented = true
				if err := Json2ReadInt64(in, &item.StepSec); err != nil {
					return err
				}
			case "utc_offset":
				if propUtcOffsetPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeLod", "utc_offset")
				}
				propUtcOffsetPresented = true
				if err := Json2ReadInt64(in, &item.UtcOffset); err != nil {
					return err
				}
			case "location":
				if propLocationPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeLod", "location")
				}
				propLocationPresented = true
				if err := Json2ReadStringBytes(in, &item.Location); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeLod", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFromSecPresented {
		item.FromSec = 0
	}
	if !propToSecPresented {
		item.ToSec = 0
	}
	if !propStepSecPresented {
		item.StepSec = 0
	}
	if !propUtcOffsetPresented {
		item.UtcOffset = 0
	}
	if !propLocationPresented {
		item.Location = item.Location[:0]
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreLodBytes) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreLodBytes) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreLodBytes) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFromSec := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"from_sec":`...)
	w = basictl.JSONWriteInt64(w, item.FromSec)
	if !(item.FromSec != 0) {
		w = w[:backupIndexFromSec]
	}
	backupIndexToSec := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"to_sec":`...)
	w = basictl.JSONWriteInt64(w, item.ToSec)
	if !(item.ToSec != 0) {
		w = w[:backupIndexToSec]
	}
	backupIndexStepSec := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"step_sec":`...)
	w = basictl.JSONWriteInt64(w, item.StepSec)
	if !(item.StepSec != 0) {
		w = w[:backupIndexStepSec]
	}
	backupIndexUtcOffset := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"utc_offset":`...)
	w = basictl.JSONWriteInt64(w, item.UtcOffset)
	if !(item.UtcOffset != 0) {
		w = w[:backupIndexUtcOffset]
	}
	backupIndexLocation := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"location":`...)
	w = basictl.JSONWriteStringBytes(w, item.Location)
	if !(len(item.Location) != 0) {
		w = w[:backupIndexLocation]
	}
	return append(w, '}')
}

func (item *StatshouseStoreLodBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreLodBytes) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeLod", err.Error())
	}
	return nil
}

func (item *StatshouseStoreLodBytes) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeLod"))
}

func (item *StatshouseStoreLodBytes) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeLod")
}
