// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type StatshouseStoreTagValuesResponse struct {
	FieldsMask uint32
	Tag        []int64
	// empty when ids_only or the tag is raw
	Stag  []string
	Count []float64
}

func (StatshouseStoreTagValuesResponse) TLName() string { return "statshouse.storeTagValuesResponse" }
func (StatshouseStoreTagValuesResponse) TLTag() uint32  { return 0x57cb1007 }

func (item *StatshouseStoreTagValuesResponse) Reset() {
	item.FieldsMask = 0
	item.Tag = item.Tag[:0]
	item.Stag = item.Stag[:0]
	item.Count = item.Count[:0]
}

func (item *StatshouseStoreTagValuesResponse) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomUint(rg)
	BuiltinVectorLongFillRandom(rg, &item.Tag)
	BuiltinVectorStringFillRandom(rg, &item.Stag)
	BuiltinVectorDoubleFillRandom(rg, &item.Count)
}

func (item *StatshouseStoreTagValuesResponse) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorLongReadTL1(w, &item.Tag); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorStringReadTL1(w, &item.Stag); err != nil {
		return w, err
	}
	return BuiltinVectorDoubleReadTL1(w, &item.Count)
}

func (item *StatshouseStoreTagValuesResponse) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreTagValuesResponse) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = BuiltinVectorLongWriteTL1(w, item.Tag)
	w = BuiltinVectorStringWriteTL1(w, item.Stag)
	w = BuiltinVectorDoubleWriteTL1(w, item.Count)
	return w
}

func (item *StatshouseStoreTagValuesResponse) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1007); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreTagValuesResponse) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreTagValuesResponse) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1007)
	return item.WriteTL1(w)
}

func (item StatshouseStoreTagValuesResponse) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreTagValuesResponse) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreTagValuesResponse) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propTagPresented bool
	var propStagPresented bool
	var propCountPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagValuesResponse", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "tag":
				if propTagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagValuesResponse", "tag")
				}
				propTagPresented = true
				if err := BuiltinVectorLongReadJSONGeneral(jctx, in, &item.Tag); err != nil {
					return err
				}
			case "stag":
				if propStagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagValuesResponse", "stag")
				}
				propStagPresented = true
				if err := BuiltinVectorStringReadJSONGeneral(jctx, in, &item.Stag); err != nil {
					return err
				}
			case "count":
				if propCountPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagValuesResponse", "count")
				}
				propCountPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Count); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeTagValuesResponse", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propTagPresented {
		item.Tag = item.Tag[:0]
	}
	if !propStagPresented {
		item.Stag = item.Stag[:0]
	}
	if !propCountPresented {
		item.Count = item.Count[:0]
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreTagValuesResponse) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreTagValuesResponse) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreTagValuesResponse) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexTag := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"tag":`...)
	w = BuiltinVectorLongWriteJSONOpt(jctx, w, item.Tag)
	if !(len(item.Tag) != 0) {
		w = w[:backupIndexTag]
	}
	backupIndexStag := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"stag":`...)
	w = BuiltinVectorStringWriteJSONOpt(jctx, w, item.Stag)
	if !(len(item.Stag) != 0) {
		w = w[:backupIndexStag]
	}
	backupIndexCount := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"count":`...)
	w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Count)
	if !(len(item.Count) != 0) {
		w = w[:backupIndexCount]
	}
	return append(w, '}')
}

func (item *StatshouseStoreTagValuesResponse) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreTagValuesResponse) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeTagValuesResponse", err.Error())
	}
	return nil
}

func (item *StatshouseStoreTagValuesResponse) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeTagValuesResponse"))
}

func (item *StatshouseStoreTagValuesResponse) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeTagValuesResponse")
}

type StatshouseStoreTagValuesResponseBytes struct {
	FieldsMask uint32
	Tag        []int64
	// empty when ids_only or the tag is raw
	Stag  [][]byte
	Count []float64
}

func (StatshouseStoreTagValuesResponseBytes) TLName() string {
	return "statshouse.storeTagValuesResponse"
}
func (StatshouseStoreTagValuesResponseBytes) TLTag() uint32 { return 0x57cb1007 }

func (item *StatshouseStoreTagValuesResponseBytes) Reset() {
	item.FieldsMask = 0
	item.Tag = item.Tag[:0]
	item.Stag = item.Stag[:0]
	item.Count = item.Count[:0]
}

func (item *StatshouseStoreTagValuesResponseBytes) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomUint(rg)
	BuiltinVectorLongFillRandom(rg, &item.Tag)
	BuiltinVectorStringBytesFillRandom(rg, &item.Stag)
	BuiltinVectorDoubleFillRandom(rg, &item.Count)
}

func (item *StatshouseStoreTagValuesResponseBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorLongReadTL1(w, &item.Tag); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorStringBytesReadTL1(w, &item.Stag); err != nil {
		return w, err
	}
	return BuiltinVectorDoubleReadTL1(w, &item.Count)
}

func (item *StatshouseStoreTagValuesResponseBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreTagValuesResponseBytes) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = BuiltinVectorLongWriteTL1(w, item.Tag)
	w = BuiltinVectorStringBytesWriteTL1(w, item.Stag)
	w = BuiltinVectorDoubleWriteTL1(w, item.Count)
	return w
}

func (item *StatshouseStoreTagValuesResponseBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1007); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreTagValuesResponseBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreTagValuesResponseBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1007)
	return item.WriteTL1(w)
}

func (item StatshouseStoreTagValuesResponseBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreTagValuesResponseBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreTagValuesResponseBytes) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propTagPresented bool
	var propStagPresented bool
	var propCountPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagValuesResponse", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "tag":
				if propTagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagValuesResponse", "tag")
				}
				propTagPresented = true
				if err := BuiltinVectorLongReadJSONGeneral(jctx, in, &item.Tag); err != nil {
					return err
				}
			case "stag":
				if propStagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagValuesResponse", "stag")
				}
				propStagPresented = true
				if err := BuiltinVectorStringBytesReadJSONGeneral(jctx, in, &item.Stag); err != nil {
					return err
				}
			case "count":
				if propCountPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagValuesResponse", "count")
				}
				propCountPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Count); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeTagValuesResponse", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propTagPresented {
		item.Tag = item.Tag[:0]
	}
	if !propStagPresented {
		item.Stag = item.Stag[:0]
	}
	if !propCountPresented {
		item.Count = item.Count[:0]
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreTagValuesResponseBytes) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreTagValuesResponseBytes) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreTagValuesResponseBytes) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexTag := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"tag":`...)
	w = BuiltinVectorLongWriteJSONOpt(jctx, w, item.Tag)
	if !(len(item.Tag) != 0) {
		w = w[:backupIndexTag]
	}
	backupIndexStag := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"stag":`...)
	w = BuiltinVectorStringBytesWriteJSONOpt(jctx, w, item.Stag)
	if !(len(item.Stag) != 0) {
		w = w[:backupIndexStag]
	}
	backupIndexCount := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"count":`...)
	w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Count)
	if !(len(item.Count) != 0) {
		w = w[:backupIndexCount]
	}
	return append(w, '}')
}

func (item *StatshouseStoreTagValuesResponseBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreTagValuesResponseBytes) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeTagValuesResponse", err.Error())
	}
	return nil
}

func (item *StatshouseStoreTagValuesResponseBytes) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeTagValuesResponse"))
}

func (item *StatshouseStoreTagValuesResponseBytes) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeTagValuesResponse")
}
