// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

func BuiltinVectorStatshouseStoreSeriesBatchBoxedFillRandom(rg *basictl.RandGenerator, vec *[]StatshouseStoreSeriesBatch) {
	rg.IncreaseDepth()
	l := basictl.RandomSize(rg)
	*vec = make([]StatshouseStoreSeriesBatch, l)
	for i := range *vec {
		(*vec)[i].FillRandom(rg)
	}
	rg.DecreaseDepth()
}
func BuiltinVectorStatshouseStoreSeriesBatchBoxedReadTL1(w []byte, vec *[]StatshouseStoreSeriesBatch) (_ []byte, err error) {
	var l uint32
	if w, err = basictl.NatRead(w, &l); err != nil {
		return w, err
	}
	if err = basictl.CheckLengthSanity(w, l, 4); err != nil {
		return w, err
	}
	if uint32(cap(*vec)) < l {
		*vec = make([]StatshouseStoreSeriesBatch, l)
	} else {
		*vec = (*vec)[:l]
	}
	for i := range *vec {
		if w, err = (*vec)[i].ReadTL1Boxed(w); err != nil {
			return w, err
		}
	}
	return w, nil
}

func BuiltinVectorStatshouseStoreSeriesBatchBoxedWriteTL1(w []byte, vec []StatshouseStoreSeriesBatch) []byte {
	w = basictl.NatWrite(w, uint32(len(vec)))
	for _, elem := range vec {
		w = elem.WriteTL1Boxed(w)
	}
	return w
}

func BuiltinVectorStatshouseStoreSeriesBatchBoxedInternalReadTL2(r []byte, vec *[]StatshouseStoreSeriesBatch) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("[]StatshouseStoreSeriesBatch")
}

func BuiltinVectorStatshouseStoreSeriesBatchBoxedReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, vec *[]StatshouseStoreSeriesBatch) error {
	*vec = (*vec)[:cap(*vec)]
	index := 0
	if in != nil {
		in.Delim('[')
		if !in.Ok() {
			return ErrorInvalidJSON("[]StatshouseStoreSeriesBatch", "expected json array")
		}
		for ; !in.IsDelim(']'); index++ {
			if len(*vec) <= index {
				var newValue StatshouseStoreSeriesBatch
				*vec = append(*vec, newValue)
				*vec = (*vec)[:cap(*vec)]
			}
			if err := (*vec)[index].ReadJSONGeneral(jctx, in); err != nil {
				return err
			}
			in.WantComma()
		}
		in.Delim(']')
		if !in.Ok() {
			return ErrorInvalidJSON("[]StatshouseStoreSeriesBatch", "expected json array's end")
		}
	}
	*vec = (*vec)[:index]
	return nil
}

func BuiltinVectorStatshouseStoreSeriesBatchBoxedWriteJSON(w []byte, vec []StatshouseStoreSeriesBatch) []byte {
	return BuiltinVectorStatshouseStoreSeriesBatchBoxedWriteJSONOpt(nil, w, vec)
}
func BuiltinVectorStatshouseStoreSeriesBatchBoxedWriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte, vec []StatshouseStoreSeriesBatch) []byte {
	w = append(w, '[')
	for _, elem := range vec {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = elem.WriteJSONOpt(jctx, w)
	}
	return append(w, ']')
}

func BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesFillRandom(rg *basictl.RandGenerator, vec *[]StatshouseStoreSeriesBatchBytes) {
	rg.IncreaseDepth()
	l := basictl.RandomSize(rg)
	*vec = make([]StatshouseStoreSeriesBatchBytes, l)
	for i := range *vec {
		(*vec)[i].FillRandom(rg)
	}
	rg.DecreaseDepth()
}
func BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesReadTL1(w []byte, vec *[]StatshouseStoreSeriesBatchBytes) (_ []byte, err error) {
	var l uint32
	if w, err = basictl.NatRead(w, &l); err != nil {
		return w, err
	}
	if err = basictl.CheckLengthSanity(w, l, 4); err != nil {
		return w, err
	}
	if uint32(cap(*vec)) < l {
		*vec = make([]StatshouseStoreSeriesBatchBytes, l)
	} else {
		*vec = (*vec)[:l]
	}
	for i := range *vec {
		if w, err = (*vec)[i].ReadTL1Boxed(w); err != nil {
			return w, err
		}
	}
	return w, nil
}

func BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesWriteTL1(w []byte, vec []StatshouseStoreSeriesBatchBytes) []byte {
	w = basictl.NatWrite(w, uint32(len(vec)))
	for _, elem := range vec {
		w = elem.WriteTL1Boxed(w)
	}
	return w
}

func BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesInternalReadTL2(r []byte, vec *[]StatshouseStoreSeriesBatchBytes) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("[]StatshouseStoreSeriesBatchBytes")
}

func BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, vec *[]StatshouseStoreSeriesBatchBytes) error {
	*vec = (*vec)[:cap(*vec)]
	index := 0
	if in != nil {
		in.Delim('[')
		if !in.Ok() {
			return ErrorInvalidJSON("[]StatshouseStoreSeriesBatchBytes", "expected json array")
		}
		for ; !in.IsDelim(']'); index++ {
			if len(*vec) <= index {
				var newValue StatshouseStoreSeriesBatchBytes
				*vec = append(*vec, newValue)
				*vec = (*vec)[:cap(*vec)]
			}
			if err := (*vec)[index].ReadJSONGeneral(jctx, in); err != nil {
				return err
			}
			in.WantComma()
		}
		in.Delim(']')
		if !in.Ok() {
			return ErrorInvalidJSON("[]StatshouseStoreSeriesBatchBytes", "expected json array's end")
		}
	}
	*vec = (*vec)[:index]
	return nil
}

func BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesWriteJSON(w []byte, vec []StatshouseStoreSeriesBatchBytes) []byte {
	return BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesWriteJSONOpt(nil, w, vec)
}
func BuiltinVectorStatshouseStoreSeriesBatchBoxedBytesWriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte, vec []StatshouseStoreSeriesBatchBytes) []byte {
	w = append(w, '[')
	for _, elem := range vec {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = elem.WriteJSONOpt(jctx, w)
	}
	return append(w, ']')
}

// One batch of columnar results; columns are parallel arrays of length `rows`.
// Forward-compatibility hinge: a later streaming verb returns the SAME type one
// batch at a time. Aggregate states ride as unmodified ClickHouse state bytes,
// never finalized — a per-shard percentile is meaningless before the API merges
// across shards and LODs. The aggregator has already folded them in Go.
// Host columns are plain (int, string) tag pairs merged by a single
// arg_min/arg_max over a struct_pack, so they ship structurally and are compared
// by value, not by bytes.
type StatshouseStoreSeriesBatch struct {
	FieldsMask uint32
	Rows       int32
	// start of each bucket, unix seconds
	Time []int64
	// one vector per grouped tag, in `by` order
	Tag [][]int64
	// parallel to `tag`; empty vector if raw
	Stag        [][]string
	Count       []float64 // Conditional: item.FieldsMask.0
	Min         []float64 // Conditional: item.FieldsMask.1
	Max         []float64 // Conditional: item.FieldsMask.2
	Sum         []float64 // Conditional: item.FieldsMask.3
	Sumsquare   []float64 // Conditional: item.FieldsMask.4
	Cardinality []float64 // Conditional: item.FieldsMask.5
	// CH quantilesTDigest state bytes
	Percentiles []string // Conditional: item.FieldsMask.6
	// CH uniq state bytes
	UniqState    []string  // Conditional: item.FieldsMask.7
	MinHostValue []float64 // Conditional: item.FieldsMask.8
	MinHostTag   []int32   // Conditional: item.FieldsMask.8
	MinHostStag  []string  // Conditional: item.FieldsMask.8
	MaxHostValue []float64 // Conditional: item.FieldsMask.9
	MaxHostTag   []int32   // Conditional: item.FieldsMask.9
	MaxHostStag  []string  // Conditional: item.FieldsMask.9
}

func (StatshouseStoreSeriesBatch) TLName() string { return "statshouse.storeSeriesBatch" }
func (StatshouseStoreSeriesBatch) TLTag() uint32  { return 0x57cb1005 }

func (item *StatshouseStoreSeriesBatch) SetCount(v []float64) {
	item.Count = v
	item.FieldsMask |= 1 << 0
}
func (item *StatshouseStoreSeriesBatch) ClearCount() {
	item.Count = item.Count[:0]
	item.FieldsMask &^= 1 << 0
}
func (item *StatshouseStoreSeriesBatch) IsSetCount() bool { return item.FieldsMask&(1<<0) != 0 }

func (item *StatshouseStoreSeriesBatch) SetMin(v []float64) {
	item.Min = v
	item.FieldsMask |= 1 << 1
}
func (item *StatshouseStoreSeriesBatch) ClearMin() {
	item.Min = item.Min[:0]
	item.FieldsMask &^= 1 << 1
}
func (item *StatshouseStoreSeriesBatch) IsSetMin() bool { return item.FieldsMask&(1<<1) != 0 }

func (item *StatshouseStoreSeriesBatch) SetMax(v []float64) {
	item.Max = v
	item.FieldsMask |= 1 << 2
}
func (item *StatshouseStoreSeriesBatch) ClearMax() {
	item.Max = item.Max[:0]
	item.FieldsMask &^= 1 << 2
}
func (item *StatshouseStoreSeriesBatch) IsSetMax() bool { return item.FieldsMask&(1<<2) != 0 }

func (item *StatshouseStoreSeriesBatch) SetSum(v []float64) {
	item.Sum = v
	item.FieldsMask |= 1 << 3
}
func (item *StatshouseStoreSeriesBatch) ClearSum() {
	item.Sum = item.Sum[:0]
	item.FieldsMask &^= 1 << 3
}
func (item *StatshouseStoreSeriesBatch) IsSetSum() bool { return item.FieldsMask&(1<<3) != 0 }

func (item *StatshouseStoreSeriesBatch) SetSumsquare(v []float64) {
	item.Sumsquare = v
	item.FieldsMask |= 1 << 4
}
func (item *StatshouseStoreSeriesBatch) ClearSumsquare() {
	item.Sumsquare = item.Sumsquare[:0]
	item.FieldsMask &^= 1 << 4
}
func (item *StatshouseStoreSeriesBatch) IsSetSumsquare() bool { return item.FieldsMask&(1<<4) != 0 }

func (item *StatshouseStoreSeriesBatch) SetCardinality(v []float64) {
	item.Cardinality = v
	item.FieldsMask |= 1 << 5
}
func (item *StatshouseStoreSeriesBatch) ClearCardinality() {
	item.Cardinality = item.Cardinality[:0]
	item.FieldsMask &^= 1 << 5
}
func (item *StatshouseStoreSeriesBatch) IsSetCardinality() bool { return item.FieldsMask&(1<<5) != 0 }

func (item *StatshouseStoreSeriesBatch) SetPercentiles(v []string) {
	item.Percentiles = v
	item.FieldsMask |= 1 << 6
}
func (item *StatshouseStoreSeriesBatch) ClearPercentiles() {
	item.Percentiles = item.Percentiles[:0]
	item.FieldsMask &^= 1 << 6
}
func (item *StatshouseStoreSeriesBatch) IsSetPercentiles() bool { return item.FieldsMask&(1<<6) != 0 }

func (item *StatshouseStoreSeriesBatch) SetUniqState(v []string) {
	item.UniqState = v
	item.FieldsMask |= 1 << 7
}
func (item *StatshouseStoreSeriesBatch) ClearUniqState() {
	item.UniqState = item.UniqState[:0]
	item.FieldsMask &^= 1 << 7
}
func (item *StatshouseStoreSeriesBatch) IsSetUniqState() bool { return item.FieldsMask&(1<<7) != 0 }

func (item *StatshouseStoreSeriesBatch) SetMinHostValue(v []float64) {
	item.MinHostValue = v
	item.FieldsMask |= 1 << 8
}
func (item *StatshouseStoreSeriesBatch) ClearMinHostValue() {
	item.MinHostValue = item.MinHostValue[:0]
	item.FieldsMask &^= 1 << 8
}
func (item *StatshouseStoreSeriesBatch) IsSetMinHostValue() bool { return item.FieldsMask&(1<<8) != 0 }

func (item *StatshouseStoreSeriesBatch) SetMinHostTag(v []int32) {
	item.MinHostTag = v
	item.FieldsMask |= 1 << 8
}
func (item *StatshouseStoreSeriesBatch) ClearMinHostTag() {
	item.MinHostTag = item.MinHostTag[:0]
	item.FieldsMask &^= 1 << 8
}
func (item *StatshouseStoreSeriesBatch) IsSetMinHostTag() bool { return item.FieldsMask&(1<<8) != 0 }

func (item *StatshouseStoreSeriesBatch) SetMinHostStag(v []string) {
	item.MinHostStag = v
	item.FieldsMask |= 1 << 8
}
func (item *StatshouseStoreSeriesBatch) ClearMinHostStag() {
	item.MinHostStag = item.MinHostStag[:0]
	item.FieldsMask &^= 1 << 8
}
func (item *StatshouseStoreSeriesBatch) IsSetMinHostStag() bool { return item.FieldsMask&(1<<8) != 0 }

func (item *StatshouseStoreSeriesBatch) SetMaxHostValue(v []float64) {
	item.MaxHostValue = v
	item.FieldsMask |= 1 << 9
}
func (item *StatshouseStoreSeriesBatch) ClearMaxHostValue() {
	item.MaxHostValue = item.MaxHostValue[:0]
	item.FieldsMask &^= 1 << 9
}
func (item *StatshouseStoreSeriesBatch) IsSetMaxHostValue() bool { return item.FieldsMask&(1<<9) != 0 }

func (item *StatshouseStoreSeriesBatch) SetMaxHostTag(v []int32) {
	item.MaxHostTag = v
	item.FieldsMask |= 1 << 9
}
func (item *StatshouseStoreSeriesBatch) ClearMaxHostTag() {
	item.MaxHostTag = item.MaxHostTag[:0]
	item.FieldsMask &^= 1 << 9
}
func (item *StatshouseStoreSeriesBatch) IsSetMaxHostTag() bool { return item.FieldsMask&(1<<9) != 0 }

func (item *StatshouseStoreSeriesBatch) SetMaxHostStag(v []string) {
	item.MaxHostStag = v
	item.FieldsMask |= 1 << 9
}
func (item *StatshouseStoreSeriesBatch) ClearMaxHostStag() {
	item.MaxHostStag = item.MaxHostStag[:0]
	item.FieldsMask &^= 1 << 9
}
func (item *StatshouseStoreSeriesBatch) IsSetMaxHostStag() bool { return item.FieldsMask&(1<<9) != 0 }

func (item *StatshouseStoreSeriesBatch) Reset() {
	item.FieldsMask = 0
	item.Rows = 0
	item.Time = item.Time[:0]
	item.Tag = item.Tag[:0]
	item.Stag = item.Stag[:0]
	item.Count = item.Count[:0]
	item.Min = item.Min[:0]
	item.Max = item.Max[:0]
	item.Sum = item.Sum[:0]
	item.Sumsquare = item.Sumsquare[:0]
	item.Cardinality = item.Cardinality[:0]
	item.Percentiles = item.Percentiles[:0]
	item.UniqState = item.UniqState[:0]
	item.MinHostValue = item.MinHostValue[:0]
	item.MinHostTag = item.MinHostTag[:0]
	item.MinHostStag = item.MinHostStag[:0]
	item.MaxHostValue = item.MaxHostValue[:0]
	item.MaxHostTag = item.MaxHostTag[:0]
	item.MaxHostStag = item.MaxHostStag[:0]
}

func (item *StatshouseStoreSeriesBatch) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b1111111111)
	item.Rows = basictl.RandomInt(rg)
	BuiltinVectorLongFillRandom(rg, &item.Time)
	BuiltinVectorVectorLongFillRandom(rg, &item.Tag)
	BuiltinVectorVectorStringFillRandom(rg, &item.Stag)
	if item.FieldsMask&(1<<0) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Count)
	} else {
		item.Count = item.Count[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Min)
	} else {
		item.Min = item.Min[:0]
	}
	if item.FieldsMask&(1<<2) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Max)
	} else {
		item.Max = item.Max[:0]
	}
	if item.FieldsMask&(1<<3) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Sum)
	} else {
		item.Sum = item.Sum[:0]
	}
	if item.FieldsMask&(1<<4) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Sumsquare)
	} else {
		item.Sumsquare = item.Sumsquare[:0]
	}
	if item.FieldsMask&(1<<5) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Cardinality)
	} else {
		item.Cardinality = item.Cardinality[:0]
	}
	if item.FieldsMask&(1<<6) != 0 {
		BuiltinVectorStringFillRandom(rg, &item.Percentiles)
	} else {
		item.Percentiles = item.Percentiles[:0]
	}
	if item.FieldsMask&(1<<7) != 0 {
		BuiltinVectorStringFillRandom(rg, &item.UniqState)
	} else {
		item.UniqState = item.UniqState[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.MinHostValue)
	} else {
		item.MinHostValue = item.MinHostValue[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		BuiltinVectorIntFillRandom(rg, &item.MinHostTag)
	} else {
		item.MinHostTag = item.MinHostTag[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		BuiltinVectorStringFillRandom(rg, &item.MinHostStag)
	} else {
		item.MinHostStag = item.MinHostStag[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.MaxHostValue)
	} else {
		item.MaxHostValue = item.MaxHostValue[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		BuiltinVectorIntFillRandom(rg, &item.MaxHostTag)
	} else {
		item.MaxHostTag = item.MaxHostTag[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		BuiltinVectorStringFillRandom(rg, &item.MaxHostStag)
	} else {
		item.MaxHostStag = item.MaxHostStag[:0]
	}
}

func (item *StatshouseStoreSeriesBatch) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.Rows); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorLongReadTL1(w, &item.Time); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorVectorLongReadTL1(w, &item.Tag); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorVectorStringReadTL1(w, &item.Stag); err != nil {
		return w, err
	}
	if item.FieldsMask&(1<<0) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Count); err != nil {
			return w, err
		}
	} else {
		item.Count = item.Count[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Min); err != nil {
			return w, err
		}
	} else {
		item.Min = item.Min[:0]
	}
	if item.FieldsMask&(1<<2) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Max); err != nil {
			return w, err
		}
	} else {
		item.Max = item.Max[:0]
	}
	if item.FieldsMask&(1<<3) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Sum); err != nil {
			return w, err
		}
	} else {
		item.Sum = item.Sum[:0]
	}
	if item.FieldsMask&(1<<4) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Sumsquare); err != nil {
			return w, err
		}
	} else {
		item.Sumsquare = item.Sumsquare[:0]
	}
	if item.FieldsMask&(1<<5) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Cardinality); err != nil {
			return w, err
		}
	} else {
		item.Cardinality = item.Cardinality[:0]
	}
	if item.FieldsMask&(1<<6) != 0 {
		if w, err = BuiltinVectorStringReadTL1(w, &item.Percentiles); err != nil {
			return w, err
		}
	} else {
		item.Percentiles = item.Percentiles[:0]
	}
	if item.FieldsMask&(1<<7) != 0 {
		if w, err = BuiltinVectorStringReadTL1(w, &item.UniqState); err != nil {
			return w, err
		}
	} else {
		item.UniqState = item.UniqState[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.MinHostValue); err != nil {
			return w, err
		}
	} else {
		item.MinHostValue = item.MinHostValue[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		if w, err = BuiltinVectorIntReadTL1(w, &item.MinHostTag); err != nil {
			return w, err
		}
	} else {
		item.MinHostTag = item.MinHostTag[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		if w, err = BuiltinVectorStringReadTL1(w, &item.MinHostStag); err != nil {
			return w, err
		}
	} else {
		item.MinHostStag = item.MinHostStag[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.MaxHostValue); err != nil {
			return w, err
		}
	} else {
		item.MaxHostValue = item.MaxHostValue[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		if w, err = BuiltinVectorIntReadTL1(w, &item.MaxHostTag); err != nil {
			return w, err
		}
	} else {
		item.MaxHostTag = item.MaxHostTag[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		if w, err = BuiltinVectorStringReadTL1(w, &item.MaxHostStag); err != nil {
			return w, err
		}
	} else {
		item.MaxHostStag = item.MaxHostStag[:0]
	}
	return w, nil
}

func (item *StatshouseStoreSeriesBatch) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreSeriesBatch) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = basictl.IntWrite(w, item.Rows)
	w = BuiltinVectorLongWriteTL1(w, item.Time)
	w = BuiltinVectorVectorLongWriteTL1(w, item.Tag)
	w = BuiltinVectorVectorStringWriteTL1(w, item.Stag)
	if item.FieldsMask&(1<<0) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Count)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Min)
	}
	if item.FieldsMask&(1<<2) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Max)
	}
	if item.FieldsMask&(1<<3) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Sum)
	}
	if item.FieldsMask&(1<<4) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Sumsquare)
	}
	if item.FieldsMask&(1<<5) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Cardinality)
	}
	if item.FieldsMask&(1<<6) != 0 {
		w = BuiltinVectorStringWriteTL1(w, item.Percentiles)
	}
	if item.FieldsMask&(1<<7) != 0 {
		w = BuiltinVectorStringWriteTL1(w, item.UniqState)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.MinHostValue)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = BuiltinVectorIntWriteTL1(w, item.MinHostTag)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = BuiltinVectorStringWriteTL1(w, item.MinHostStag)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.MaxHostValue)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = BuiltinVectorIntWriteTL1(w, item.MaxHostTag)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = BuiltinVectorStringWriteTL1(w, item.MaxHostStag)
	}
	return w
}

func (item *StatshouseStoreSeriesBatch) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1005); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreSeriesBatch) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreSeriesBatch) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1005)
	return item.WriteTL1(w)
}

func (item StatshouseStoreSeriesBatch) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreSeriesBatch) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreSeriesBatch) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propRowsPresented bool
	var propTimePresented bool
	var propTagPresented bool
	var propStagPresented bool
	var propCountPresented bool
	var propMinPresented bool
	var propMaxPresented bool
	var propSumPresented bool
	var propSumsquarePresented bool
	var propCardinalityPresented bool
	var propPercentilesPresented bool
	var propUniqStatePresented bool
	var propMinHostValuePresented bool
	var propMinHostTagPresented bool
	var propMinHostStagPresented bool
	var propMaxHostValuePresented bool
	var propMaxHostTagPresented bool
	var propMaxHostStagPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "rows":
				if propRowsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "rows")
				}
				propRowsPresented = true
				if err := Json2ReadInt32(in, &item.Rows); err != nil {
					return err
				}
			case "time":
				if propTimePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "time")
				}
				propTimePresented = true
				if err := BuiltinVectorLongReadJSONGeneral(jctx, in, &item.Time); err != nil {
					return err
				}
			case "tag":
				if propTagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "tag")
				}
				propTagPresented = true
				if err := BuiltinVectorVectorLongReadJSONGeneral(jctx, in, &item.Tag); err != nil {
					return err
				}
			case "stag":
				if propStagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "stag")
				}
				propStagPresented = true
				if err := BuiltinVectorVectorStringReadJSONGeneral(jctx, in, &item.Stag); err != nil {
					return err
				}
			case "count":
				if propCountPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "count")
				}
				propCountPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Count); err != nil {
					return err
				}
			case "min":
				if propMinPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "min")
				}
				propMinPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Min); err != nil {
					return err
				}
			case "max":
				if propMaxPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "max")
				}
				propMaxPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Max); err != nil {
					return err
				}
			case "sum":
				if propSumPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "sum")
				}
				propSumPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Sum); err != nil {
					return err
				}
			case "sumsquare":
				if propSumsquarePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "sumsquare")
				}
				propSumsquarePresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Sumsquare); err != nil {
					return err
				}
			case "cardinality":
				if propCardinalityPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "cardinality")
				}
				propCardinalityPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Cardinality); err != nil {
					return err
				}
			case "percentiles":
				if propPercentilesPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "percentiles")
				}
				propPercentilesPresented = true
				if err := BuiltinVectorStringReadJSONGeneral(jctx, in, &item.Percentiles); err != nil {
					return err
				}
			case "uniq_state":
				if propUniqStatePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "uniq_state")
				}
				propUniqStatePresented = true
				if err := BuiltinVectorStringReadJSONGeneral(jctx, in, &item.UniqState); err != nil {
					return err
				}
			case "min_host_value":
				if propMinHostValuePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "min_host_value")
				}
				propMinHostValuePresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.MinHostValue); err != nil {
					return err
				}
			case "min_host_tag":
				if propMinHostTagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "min_host_tag")
				}
				propMinHostTagPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.MinHostTag); err != nil {
					return err
				}
			case "min_host_stag":
				if propMinHostStagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "min_host_stag")
				}
				propMinHostStagPresented = true
				if err := BuiltinVectorStringReadJSONGeneral(jctx, in, &item.MinHostStag); err != nil {
					return err
				}
			case "max_host_value":
				if propMaxHostValuePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "max_host_value")
				}
				propMaxHostValuePresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.MaxHostValue); err != nil {
					return err
				}
			case "max_host_tag":
				if propMaxHostTagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "max_host_tag")
				}
				propMaxHostTagPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.MaxHostTag); err != nil {
					return err
				}
			case "max_host_stag":
				if propMaxHostStagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "max_host_stag")
				}
				propMaxHostStagPresented = true
				if err := BuiltinVectorStringReadJSONGeneral(jctx, in, &item.MaxHostStag); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeSeriesBatch", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propRowsPresented {
		item.Rows = 0
	}
	if !propTimePresented {
		item.Time = item.Time[:0]
	}
	if !propTagPresented {
		item.Tag = item.Tag[:0]
	}
	if !propStagPresented {
		item.Stag = item.Stag[:0]
	}
	if !propCountPresented {
		item.Count = item.Count[:0]
	}
	if !propMinPresented {
		item.Min = item.Min[:0]
	}
	if !propMaxPresented {
		item.Max = item.Max[:0]
	}
	if !propSumPresented {
		item.Sum = item.Sum[:0]
	}
	if !propSumsquarePresented {
		item.Sumsquare = item.Sumsquare[:0]
	}
	if !propCardinalityPresented {
		item.Cardinality = item.Cardinality[:0]
	}
	if !propPercentilesPresented {
		item.Percentiles = item.Percentiles[:0]
	}
	if !propUniqStatePresented {
		item.UniqState = item.UniqState[:0]
	}
	if !propMinHostValuePresented {
		item.MinHostValue = item.MinHostValue[:0]
	}
	if !propMinHostTagPresented {
		item.MinHostTag = item.MinHostTag[:0]
	}
	if !propMinHostStagPresented {
		item.MinHostStag = item.MinHostStag[:0]
	}
	if !propMaxHostValuePresented {
		item.MaxHostValue = item.MaxHostValue[:0]
	}
	if !propMaxHostTagPresented {
		item.MaxHostTag = item.MaxHostTag[:0]
	}
	if !propMaxHostStagPresented {
		item.MaxHostStag = item.MaxHostStag[:0]
	}
	if propCountPresented {
		item.FieldsMask |= 1 << 0
	}
	if propMinPresented {
		item.FieldsMask |= 1 << 1
	}
	if propMaxPresented {
		item.FieldsMask |= 1 << 2
	}
	if propSumPresented {
		item.FieldsMask |= 1 << 3
	}
	if propSumsquarePresented {
		item.FieldsMask |= 1 << 4
	}
	if propCardinalityPresented {
		item.FieldsMask |= 1 << 5
	}
	if propPercentilesPresented {
		item.FieldsMask |= 1 << 6
	}
	if propUniqStatePresented {
		item.FieldsMask |= 1 << 7
	}
	if propMinHostValuePresented {
		item.FieldsMask |= 1 << 8
	}
	if propMinHostTagPresented {
		item.FieldsMask |= 1 << 8
	}
	if propMinHostStagPresented {
		item.FieldsMask |= 1 << 8
	}
	if propMaxHostValuePresented {
		item.FieldsMask |= 1 << 9
	}
	if propMaxHostTagPresented {
		item.FieldsMask |= 1 << 9
	}
	if propMaxHostStagPresented {
		item.FieldsMask |= 1 << 9
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreSeriesBatch) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreSeriesBatch) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreSeriesBatch) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexRows := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"rows":`...)
	w = basictl.JSONWriteInt32(w, item.Rows)
	if !(item.Rows != 0) {
		w = w[:backupIndexRows]
	}
	backupIndexTime := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"time":`...)
	w = BuiltinVectorLongWriteJSONOpt(jctx, w, item.Time)
	if !(len(item.Time) != 0) {
		w = w[:backupIndexTime]
	}
	backupIndexTag := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"tag":`...)
	w = BuiltinVectorVectorLongWriteJSONOpt(jctx, w, item.Tag)
	if !(len(item.Tag) != 0) {
		w = w[:backupIndexTag]
	}
	backupIndexStag := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"stag":`...)
	w = BuiltinVectorVectorStringWriteJSONOpt(jctx, w, item.Stag)
	if !(len(item.Stag) != 0) {
		w = w[:backupIndexStag]
	}
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"count":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Count)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"min":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Min)
	}
	if item.FieldsMask&(1<<2) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"max":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Max)
	}
	if item.FieldsMask&(1<<3) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"sum":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Sum)
	}
	if item.FieldsMask&(1<<4) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"sumsquare":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Sumsquare)
	}
	if item.FieldsMask&(1<<5) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"cardinality":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Cardinality)
	}
	if item.FieldsMask&(1<<6) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"percentiles":`...)
		w = BuiltinVectorStringWriteJSONOpt(jctx, w, item.Percentiles)
	}
	if item.FieldsMask&(1<<7) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"uniq_state":`...)
		w = BuiltinVectorStringWriteJSONOpt(jctx, w, item.UniqState)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"min_host_value":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.MinHostValue)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"min_host_tag":`...)
		w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.MinHostTag)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"min_host_stag":`...)
		w = BuiltinVectorStringWriteJSONOpt(jctx, w, item.MinHostStag)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"max_host_value":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.MaxHostValue)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"max_host_tag":`...)
		w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.MaxHostTag)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"max_host_stag":`...)
		w = BuiltinVectorStringWriteJSONOpt(jctx, w, item.MaxHostStag)
	}
	return append(w, '}')
}

func (item *StatshouseStoreSeriesBatch) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreSeriesBatch) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeSeriesBatch", err.Error())
	}
	return nil
}

func (item *StatshouseStoreSeriesBatch) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeSeriesBatch"))
}

func (item *StatshouseStoreSeriesBatch) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeSeriesBatch")
}

// One batch of columnar results; columns are parallel arrays of length `rows`.
// Forward-compatibility hinge: a later streaming verb returns the SAME type one
// batch at a time. Aggregate states ride as unmodified ClickHouse state bytes,
// never finalized — a per-shard percentile is meaningless before the API merges
// across shards and LODs. The aggregator has already folded them in Go.
// Host columns are plain (int, string) tag pairs merged by a single
// arg_min/arg_max over a struct_pack, so they ship structurally and are compared
// by value, not by bytes.
type StatshouseStoreSeriesBatchBytes struct {
	FieldsMask uint32
	Rows       int32
	// start of each bucket, unix seconds
	Time []int64
	// one vector per grouped tag, in `by` order
	Tag [][]int64
	// parallel to `tag`; empty vector if raw
	Stag        [][][]byte
	Count       []float64 // Conditional: item.FieldsMask.0
	Min         []float64 // Conditional: item.FieldsMask.1
	Max         []float64 // Conditional: item.FieldsMask.2
	Sum         []float64 // Conditional: item.FieldsMask.3
	Sumsquare   []float64 // Conditional: item.FieldsMask.4
	Cardinality []float64 // Conditional: item.FieldsMask.5
	// CH quantilesTDigest state bytes
	Percentiles [][]byte // Conditional: item.FieldsMask.6
	// CH uniq state bytes
	UniqState    [][]byte  // Conditional: item.FieldsMask.7
	MinHostValue []float64 // Conditional: item.FieldsMask.8
	MinHostTag   []int32   // Conditional: item.FieldsMask.8
	MinHostStag  [][]byte  // Conditional: item.FieldsMask.8
	MaxHostValue []float64 // Conditional: item.FieldsMask.9
	MaxHostTag   []int32   // Conditional: item.FieldsMask.9
	MaxHostStag  [][]byte  // Conditional: item.FieldsMask.9
}

func (StatshouseStoreSeriesBatchBytes) TLName() string { return "statshouse.storeSeriesBatch" }
func (StatshouseStoreSeriesBatchBytes) TLTag() uint32  { return 0x57cb1005 }

func (item *StatshouseStoreSeriesBatchBytes) SetCount(v []float64) {
	item.Count = v
	item.FieldsMask |= 1 << 0
}
func (item *StatshouseStoreSeriesBatchBytes) ClearCount() {
	item.Count = item.Count[:0]
	item.FieldsMask &^= 1 << 0
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetCount() bool { return item.FieldsMask&(1<<0) != 0 }

func (item *StatshouseStoreSeriesBatchBytes) SetMin(v []float64) {
	item.Min = v
	item.FieldsMask |= 1 << 1
}
func (item *StatshouseStoreSeriesBatchBytes) ClearMin() {
	item.Min = item.Min[:0]
	item.FieldsMask &^= 1 << 1
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetMin() bool { return item.FieldsMask&(1<<1) != 0 }

func (item *StatshouseStoreSeriesBatchBytes) SetMax(v []float64) {
	item.Max = v
	item.FieldsMask |= 1 << 2
}
func (item *StatshouseStoreSeriesBatchBytes) ClearMax() {
	item.Max = item.Max[:0]
	item.FieldsMask &^= 1 << 2
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetMax() bool { return item.FieldsMask&(1<<2) != 0 }

func (item *StatshouseStoreSeriesBatchBytes) SetSum(v []float64) {
	item.Sum = v
	item.FieldsMask |= 1 << 3
}
func (item *StatshouseStoreSeriesBatchBytes) ClearSum() {
	item.Sum = item.Sum[:0]
	item.FieldsMask &^= 1 << 3
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetSum() bool { return item.FieldsMask&(1<<3) != 0 }

func (item *StatshouseStoreSeriesBatchBytes) SetSumsquare(v []float64) {
	item.Sumsquare = v
	item.FieldsMask |= 1 << 4
}
func (item *StatshouseStoreSeriesBatchBytes) ClearSumsquare() {
	item.Sumsquare = item.Sumsquare[:0]
	item.FieldsMask &^= 1 << 4
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetSumsquare() bool {
	return item.FieldsMask&(1<<4) != 0
}

func (item *StatshouseStoreSeriesBatchBytes) SetCardinality(v []float64) {
	item.Cardinality = v
	item.FieldsMask |= 1 << 5
}
func (item *StatshouseStoreSeriesBatchBytes) ClearCardinality() {
	item.Cardinality = item.Cardinality[:0]
	item.FieldsMask &^= 1 << 5
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetCardinality() bool {
	return item.FieldsMask&(1<<5) != 0
}

func (item *StatshouseStoreSeriesBatchBytes) SetPercentiles(v [][]byte) {
	item.Percentiles = v
	item.FieldsMask |= 1 << 6
}
func (item *StatshouseStoreSeriesBatchBytes) ClearPercentiles() {
	item.Percentiles = item.Percentiles[:0]
	item.FieldsMask &^= 1 << 6
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetPercentiles() bool {
	return item.FieldsMask&(1<<6) != 0
}

func (item *StatshouseStoreSeriesBatchBytes) SetUniqState(v [][]byte) {
	item.UniqState = v
	item.FieldsMask |= 1 << 7
}
func (item *StatshouseStoreSeriesBatchBytes) ClearUniqState() {
	item.UniqState = item.UniqState[:0]
	item.FieldsMask &^= 1 << 7
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetUniqState() bool {
	return item.FieldsMask&(1<<7) != 0
}

func (item *StatshouseStoreSeriesBatchBytes) SetMinHostValue(v []float64) {
	item.MinHostValue = v
	item.FieldsMask |= 1 << 8
}
func (item *StatshouseStoreSeriesBatchBytes) ClearMinHostValue() {
	item.MinHostValue = item.MinHostValue[:0]
	item.FieldsMask &^= 1 << 8
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetMinHostValue() bool {
	return item.FieldsMask&(1<<8) != 0
}

func (item *StatshouseStoreSeriesBatchBytes) SetMinHostTag(v []int32) {
	item.MinHostTag = v
	item.FieldsMask |= 1 << 8
}
func (item *StatshouseStoreSeriesBatchBytes) ClearMinHostTag() {
	item.MinHostTag = item.MinHostTag[:0]
	item.FieldsMask &^= 1 << 8
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetMinHostTag() bool {
	return item.FieldsMask&(1<<8) != 0
}

func (item *StatshouseStoreSeriesBatchBytes) SetMinHostStag(v [][]byte) {
	item.MinHostStag = v
	item.FieldsMask |= 1 << 8
}
func (item *StatshouseStoreSeriesBatchBytes) ClearMinHostStag() {
	item.MinHostStag = item.MinHostStag[:0]
	item.FieldsMask &^= 1 << 8
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetMinHostStag() bool {
	return item.FieldsMask&(1<<8) != 0
}

func (item *StatshouseStoreSeriesBatchBytes) SetMaxHostValue(v []float64) {
	item.MaxHostValue = v
	item.FieldsMask |= 1 << 9
}
func (item *StatshouseStoreSeriesBatchBytes) ClearMaxHostValue() {
	item.MaxHostValue = item.MaxHostValue[:0]
	item.FieldsMask &^= 1 << 9
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetMaxHostValue() bool {
	return item.FieldsMask&(1<<9) != 0
}

func (item *StatshouseStoreSeriesBatchBytes) SetMaxHostTag(v []int32) {
	item.MaxHostTag = v
	item.FieldsMask |= 1 << 9
}
func (item *StatshouseStoreSeriesBatchBytes) ClearMaxHostTag() {
	item.MaxHostTag = item.MaxHostTag[:0]
	item.FieldsMask &^= 1 << 9
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetMaxHostTag() bool {
	return item.FieldsMask&(1<<9) != 0
}

func (item *StatshouseStoreSeriesBatchBytes) SetMaxHostStag(v [][]byte) {
	item.MaxHostStag = v
	item.FieldsMask |= 1 << 9
}
func (item *StatshouseStoreSeriesBatchBytes) ClearMaxHostStag() {
	item.MaxHostStag = item.MaxHostStag[:0]
	item.FieldsMask &^= 1 << 9
}
func (item *StatshouseStoreSeriesBatchBytes) IsSetMaxHostStag() bool {
	return item.FieldsMask&(1<<9) != 0
}

func (item *StatshouseStoreSeriesBatchBytes) Reset() {
	item.FieldsMask = 0
	item.Rows = 0
	item.Time = item.Time[:0]
	item.Tag = item.Tag[:0]
	item.Stag = item.Stag[:0]
	item.Count = item.Count[:0]
	item.Min = item.Min[:0]
	item.Max = item.Max[:0]
	item.Sum = item.Sum[:0]
	item.Sumsquare = item.Sumsquare[:0]
	item.Cardinality = item.Cardinality[:0]
	item.Percentiles = item.Percentiles[:0]
	item.UniqState = item.UniqState[:0]
	item.MinHostValue = item.MinHostValue[:0]
	item.MinHostTag = item.MinHostTag[:0]
	item.MinHostStag = item.MinHostStag[:0]
	item.MaxHostValue = item.MaxHostValue[:0]
	item.MaxHostTag = item.MaxHostTag[:0]
	item.MaxHostStag = item.MaxHostStag[:0]
}

func (item *StatshouseStoreSeriesBatchBytes) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b1111111111)
	item.Rows = basictl.RandomInt(rg)
	BuiltinVectorLongFillRandom(rg, &item.Time)
	BuiltinVectorVectorLongFillRandom(rg, &item.Tag)
	BuiltinVectorVectorStringBytesFillRandom(rg, &item.Stag)
	if item.FieldsMask&(1<<0) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Count)
	} else {
		item.Count = item.Count[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Min)
	} else {
		item.Min = item.Min[:0]
	}
	if item.FieldsMask&(1<<2) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Max)
	} else {
		item.Max = item.Max[:0]
	}
	if item.FieldsMask&(1<<3) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Sum)
	} else {
		item.Sum = item.Sum[:0]
	}
	if item.FieldsMask&(1<<4) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Sumsquare)
	} else {
		item.Sumsquare = item.Sumsquare[:0]
	}
	if item.FieldsMask&(1<<5) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.Cardinality)
	} else {
		item.Cardinality = item.Cardinality[:0]
	}
	if item.FieldsMask&(1<<6) != 0 {
		BuiltinVectorStringBytesFillRandom(rg, &item.Percentiles)
	} else {
		item.Percentiles = item.Percentiles[:0]
	}
	if item.FieldsMask&(1<<7) != 0 {
		BuiltinVectorStringBytesFillRandom(rg, &item.UniqState)
	} else {
		item.UniqState = item.UniqState[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.MinHostValue)
	} else {
		item.MinHostValue = item.MinHostValue[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		BuiltinVectorIntFillRandom(rg, &item.MinHostTag)
	} else {
		item.MinHostTag = item.MinHostTag[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		BuiltinVectorStringBytesFillRandom(rg, &item.MinHostStag)
	} else {
		item.MinHostStag = item.MinHostStag[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		BuiltinVectorDoubleFillRandom(rg, &item.MaxHostValue)
	} else {
		item.MaxHostValue = item.MaxHostValue[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		BuiltinVectorIntFillRandom(rg, &item.MaxHostTag)
	} else {
		item.MaxHostTag = item.MaxHostTag[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		BuiltinVectorStringBytesFillRandom(rg, &item.MaxHostStag)
	} else {
		item.MaxHostStag = item.MaxHostStag[:0]
	}
}

func (item *StatshouseStoreSeriesBatchBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.Rows); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorLongReadTL1(w, &item.Time); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorVectorLongReadTL1(w, &item.Tag); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorVectorStringBytesReadTL1(w, &item.Stag); err != nil {
		return w, err
	}
	if item.FieldsMask&(1<<0) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Count); err != nil {
			return w, err
		}
	} else {
		item.Count = item.Count[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Min); err != nil {
			return w, err
		}
	} else {
		item.Min = item.Min[:0]
	}
	if item.FieldsMask&(1<<2) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Max); err != nil {
			return w, err
		}
	} else {
		item.Max = item.Max[:0]
	}
	if item.FieldsMask&(1<<3) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Sum); err != nil {
			return w, err
		}
	} else {
		item.Sum = item.Sum[:0]
	}
	if item.FieldsMask&(1<<4) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Sumsquare); err != nil {
			return w, err
		}
	} else {
		item.Sumsquare = item.Sumsquare[:0]
	}
	if item.FieldsMask&(1<<5) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.Cardinality); err != nil {
			return w, err
		}
	} else {
		item.Cardinality = item.Cardinality[:0]
	}
	if item.FieldsMask&(1<<6) != 0 {
		if w, err = BuiltinVectorStringBytesReadTL1(w, &item.Percentiles); err != nil {
			return w, err
		}
	} else {
		item.Percentiles = item.Percentiles[:0]
	}
	if item.FieldsMask&(1<<7) != 0 {
		if w, err = BuiltinVectorStringBytesReadTL1(w, &item.UniqState); err != nil {
			return w, err
		}
	} else {
		item.UniqState = item.UniqState[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.MinHostValue); err != nil {
			return w, err
		}
	} else {
		item.MinHostValue = item.MinHostValue[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		if w, err = BuiltinVectorIntReadTL1(w, &item.MinHostTag); err != nil {
			return w, err
		}
	} else {
		item.MinHostTag = item.MinHostTag[:0]
	}
	if item.FieldsMask&(1<<8) != 0 {
		if w, err = BuiltinVectorStringBytesReadTL1(w, &item.MinHostStag); err != nil {
			return w, err
		}
	} else {
		item.MinHostStag = item.MinHostStag[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		if w, err = BuiltinVectorDoubleReadTL1(w, &item.MaxHostValue); err != nil {
			return w, err
		}
	} else {
		item.MaxHostValue = item.MaxHostValue[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		if w, err = BuiltinVectorIntReadTL1(w, &item.MaxHostTag); err != nil {
			return w, err
		}
	} else {
		item.MaxHostTag = item.MaxHostTag[:0]
	}
	if item.FieldsMask&(1<<9) != 0 {
		if w, err = BuiltinVectorStringBytesReadTL1(w, &item.MaxHostStag); err != nil {
			return w, err
		}
	} else {
		item.MaxHostStag = item.MaxHostStag[:0]
	}
	return w, nil
}

func (item *StatshouseStoreSeriesBatchBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreSeriesBatchBytes) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = basictl.IntWrite(w, item.Rows)
	w = BuiltinVectorLongWriteTL1(w, item.Time)
	w = BuiltinVectorVectorLongWriteTL1(w, item.Tag)
	w = BuiltinVectorVectorStringBytesWriteTL1(w, item.Stag)
	if item.FieldsMask&(1<<0) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Count)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Min)
	}
	if item.FieldsMask&(1<<2) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Max)
	}
	if item.FieldsMask&(1<<3) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Sum)
	}
	if item.FieldsMask&(1<<4) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Sumsquare)
	}
	if item.FieldsMask&(1<<5) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.Cardinality)
	}
	if item.FieldsMask&(1<<6) != 0 {
		w = BuiltinVectorStringBytesWriteTL1(w, item.Percentiles)
	}
	if item.FieldsMask&(1<<7) != 0 {
		w = BuiltinVectorStringBytesWriteTL1(w, item.UniqState)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.MinHostValue)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = BuiltinVectorIntWriteTL1(w, item.MinHostTag)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = BuiltinVectorStringBytesWriteTL1(w, item.MinHostStag)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = BuiltinVectorDoubleWriteTL1(w, item.MaxHostValue)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = BuiltinVectorIntWriteTL1(w, item.MaxHostTag)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = BuiltinVectorStringBytesWriteTL1(w, item.MaxHostStag)
	}
	return w
}

func (item *StatshouseStoreSeriesBatchBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1005); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreSeriesBatchBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreSeriesBatchBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1005)
	return item.WriteTL1(w)
}

func (item StatshouseStoreSeriesBatchBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreSeriesBatchBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreSeriesBatchBytes) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propRowsPresented bool
	var propTimePresented bool
	var propTagPresented bool
	var propStagPresented bool
	var propCountPresented bool
	var propMinPresented bool
	var propMaxPresented bool
	var propSumPresented bool
	var propSumsquarePresented bool
	var propCardinalityPresented bool
	var propPercentilesPresented bool
	var propUniqStatePresented bool
	var propMinHostValuePresented bool
	var propMinHostTagPresented bool
	var propMinHostStagPresented bool
	var propMaxHostValuePresented bool
	var propMaxHostTagPresented bool
	var propMaxHostStagPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "rows":
				if propRowsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "rows")
				}
				propRowsPresented = true
				if err := Json2ReadInt32(in, &item.Rows); err != nil {
					return err
				}
			case "time":
				if propTimePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "time")
				}
				propTimePresented = true
				if err := BuiltinVectorLongReadJSONGeneral(jctx, in, &item.Time); err != nil {
					return err
				}
			case "tag":
				if propTagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "tag")
				}
				propTagPresented = true
				if err := BuiltinVectorVectorLongReadJSONGeneral(jctx, in, &item.Tag); err != nil {
					return err
				}
			case "stag":
				if propStagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "stag")
				}
				propStagPresented = true
				if err := BuiltinVectorVectorStringBytesReadJSONGeneral(jctx, in, &item.Stag); err != nil {
					return err
				}
			case "count":
				if propCountPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "count")
				}
				propCountPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Count); err != nil {
					return err
				}
			case "min":
				if propMinPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "min")
				}
				propMinPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Min); err != nil {
					return err
				}
			case "max":
				if propMaxPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "max")
				}
				propMaxPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Max); err != nil {
					return err
				}
			case "sum":
				if propSumPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "sum")
				}
				propSumPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Sum); err != nil {
					return err
				}
			case "sumsquare":
				if propSumsquarePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "sumsquare")
				}
				propSumsquarePresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Sumsquare); err != nil {
					return err
				}
			case "cardinality":
				if propCardinalityPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "cardinality")
				}
				propCardinalityPresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.Cardinality); err != nil {
					return err
				}
			case "percentiles":
				if propPercentilesPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "percentiles")
				}
				propPercentilesPresented = true
				if err := BuiltinVectorStringBytesReadJSONGeneral(jctx, in, &item.Percentiles); err != nil {
					return err
				}
			case "uniq_state":
				if propUniqStatePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "uniq_state")
				}
				propUniqStatePresented = true
				if err := BuiltinVectorStringBytesReadJSONGeneral(jctx, in, &item.UniqState); err != nil {
					return err
				}
			case "min_host_value":
				if propMinHostValuePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "min_host_value")
				}
				propMinHostValuePresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.MinHostValue); err != nil {
					return err
				}
			case "min_host_tag":
				if propMinHostTagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "min_host_tag")
				}
				propMinHostTagPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.MinHostTag); err != nil {
					return err
				}
			case "min_host_stag":
				if propMinHostStagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "min_host_stag")
				}
				propMinHostStagPresented = true
				if err := BuiltinVectorStringBytesReadJSONGeneral(jctx, in, &item.MinHostStag); err != nil {
					return err
				}
			case "max_host_value":
				if propMaxHostValuePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "max_host_value")
				}
				propMaxHostValuePresented = true
				if err := BuiltinVectorDoubleReadJSONGeneral(jctx, in, &item.MaxHostValue); err != nil {
					return err
				}
			case "max_host_tag":
				if propMaxHostTagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "max_host_tag")
				}
				propMaxHostTagPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.MaxHostTag); err != nil {
					return err
				}
			case "max_host_stag":
				if propMaxHostStagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeSeriesBatch", "max_host_stag")
				}
				propMaxHostStagPresented = true
				if err := BuiltinVectorStringBytesReadJSONGeneral(jctx, in, &item.MaxHostStag); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeSeriesBatch", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propRowsPresented {
		item.Rows = 0
	}
	if !propTimePresented {
		item.Time = item.Time[:0]
	}
	if !propTagPresented {
		item.Tag = item.Tag[:0]
	}
	if !propStagPresented {
		item.Stag = item.Stag[:0]
	}
	if !propCountPresented {
		item.Count = item.Count[:0]
	}
	if !propMinPresented {
		item.Min = item.Min[:0]
	}
	if !propMaxPresented {
		item.Max = item.Max[:0]
	}
	if !propSumPresented {
		item.Sum = item.Sum[:0]
	}
	if !propSumsquarePresented {
		item.Sumsquare = item.Sumsquare[:0]
	}
	if !propCardinalityPresented {
		item.Cardinality = item.Cardinality[:0]
	}
	if !propPercentilesPresented {
		item.Percentiles = item.Percentiles[:0]
	}
	if !propUniqStatePresented {
		item.UniqState = item.UniqState[:0]
	}
	if !propMinHostValuePresented {
		item.MinHostValue = item.MinHostValue[:0]
	}
	if !propMinHostTagPresented {
		item.MinHostTag = item.MinHostTag[:0]
	}
	if !propMinHostStagPresented {
		item.MinHostStag = item.MinHostStag[:0]
	}
	if !propMaxHostValuePresented {
		item.MaxHostValue = item.MaxHostValue[:0]
	}
	if !propMaxHostTagPresented {
		item.MaxHostTag = item.MaxHostTag[:0]
	}
	if !propMaxHostStagPresented {
		item.MaxHostStag = item.MaxHostStag[:0]
	}
	if propCountPresented {
		item.FieldsMask |= 1 << 0
	}
	if propMinPresented {
		item.FieldsMask |= 1 << 1
	}
	if propMaxPresented {
		item.FieldsMask |= 1 << 2
	}
	if propSumPresented {
		item.FieldsMask |= 1 << 3
	}
	if propSumsquarePresented {
		item.FieldsMask |= 1 << 4
	}
	if propCardinalityPresented {
		item.FieldsMask |= 1 << 5
	}
	if propPercentilesPresented {
		item.FieldsMask |= 1 << 6
	}
	if propUniqStatePresented {
		item.FieldsMask |= 1 << 7
	}
	if propMinHostValuePresented {
		item.FieldsMask |= 1 << 8
	}
	if propMinHostTagPresented {
		item.FieldsMask |= 1 << 8
	}
	if propMinHostStagPresented {
		item.FieldsMask |= 1 << 8
	}
	if propMaxHostValuePresented {
		item.FieldsMask |= 1 << 9
	}
	if propMaxHostTagPresented {
		item.FieldsMask |= 1 << 9
	}
	if propMaxHostStagPresented {
		item.FieldsMask |= 1 << 9
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreSeriesBatchBytes) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreSeriesBatchBytes) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreSeriesBatchBytes) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexRows := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"rows":`...)
	w = basictl.JSONWriteInt32(w, item.Rows)
	if !(item.Rows != 0) {
		w = w[:backupIndexRows]
	}
	backupIndexTime := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"time":`...)
	w = BuiltinVectorLongWriteJSONOpt(jctx, w, item.Time)
	if !(len(item.Time) != 0) {
		w = w[:backupIndexTime]
	}
	backupIndexTag := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"tag":`...)
	w = BuiltinVectorVectorLongWriteJSONOpt(jctx, w, item.Tag)
	if !(len(item.Tag) != 0) {
		w = w[:backupIndexTag]
	}
	backupIndexStag := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"stag":`...)
	w = BuiltinVectorVectorStringBytesWriteJSONOpt(jctx, w, item.Stag)
	if !(len(item.Stag) != 0) {
		w = w[:backupIndexStag]
	}
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"count":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Count)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"min":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Min)
	}
	if item.FieldsMask&(1<<2) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"max":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Max)
	}
	if item.FieldsMask&(1<<3) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"sum":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Sum)
	}
	if item.FieldsMask&(1<<4) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"sumsquare":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Sumsquare)
	}
	if item.FieldsMask&(1<<5) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"cardinality":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.Cardinality)
	}
	if item.FieldsMask&(1<<6) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"percentiles":`...)
		w = BuiltinVectorStringBytesWriteJSONOpt(jctx, w, item.Percentiles)
	}
	if item.FieldsMask&(1<<7) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"uniq_state":`...)
		w = BuiltinVectorStringBytesWriteJSONOpt(jctx, w, item.UniqState)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"min_host_value":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.MinHostValue)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"min_host_tag":`...)
		w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.MinHostTag)
	}
	if item.FieldsMask&(1<<8) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"min_host_stag":`...)
		w = BuiltinVectorStringBytesWriteJSONOpt(jctx, w, item.MinHostStag)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"max_host_value":`...)
		w = BuiltinVectorDoubleWriteJSONOpt(jctx, w, item.MaxHostValue)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"max_host_tag":`...)
		w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.MaxHostTag)
	}
	if item.FieldsMask&(1<<9) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"max_host_stag":`...)
		w = BuiltinVectorStringBytesWriteJSONOpt(jctx, w, item.MaxHostStag)
	}
	return append(w, '}')
}

func (item *StatshouseStoreSeriesBatchBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreSeriesBatchBytes) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeSeriesBatch", err.Error())
	}
	return nil
}

func (item *StatshouseStoreSeriesBatchBytes) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeSeriesBatch"))
}

func (item *StatshouseStoreSeriesBatchBytes) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeSeriesBatch")
}
