// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

func BuiltinVectorStatshouseStoreTagFilterBoxedFillRandom(rg *basictl.RandGenerator, vec *[]StatshouseStoreTagFilter) {
	rg.IncreaseDepth()
	l := basictl.RandomSize(rg)
	*vec = make([]StatshouseStoreTagFilter, l)
	for i := range *vec {
		(*vec)[i].FillRandom(rg)
	}
	rg.DecreaseDepth()
}
func BuiltinVectorStatshouseStoreTagFilterBoxedReadTL1(w []byte, vec *[]StatshouseStoreTagFilter) (_ []byte, err error) {
	var l uint32
	if w, err = basictl.NatRead(w, &l); err != nil {
		return w, err
	}
	if err = basictl.CheckLengthSanity(w, l, 4); err != nil {
		return w, err
	}
	if uint32(cap(*vec)) < l {
		*vec = make([]StatshouseStoreTagFilter, l)
	} else {
		*vec = (*vec)[:l]
	}
	for i := range *vec {
		if w, err = (*vec)[i].ReadTL1Boxed(w); err != nil {
			return w, err
		}
	}
	return w, nil
}

func BuiltinVectorStatshouseStoreTagFilterBoxedWriteTL1(w []byte, vec []StatshouseStoreTagFilter) []byte {
	w = basictl.NatWrite(w, uint32(len(vec)))
	for _, elem := range vec {
		w = elem.WriteTL1Boxed(w)
	}
	return w
}

func BuiltinVectorStatshouseStoreTagFilterBoxedInternalReadTL2(r []byte, vec *[]StatshouseStoreTagFilter) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("[]StatshouseStoreTagFilter")
}

func BuiltinVectorStatshouseStoreTagFilterBoxedReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, vec *[]StatshouseStoreTagFilter) error {
	*vec = (*vec)[:cap(*vec)]
	index := 0
	if in != nil {
		in.Delim('[')
		if !in.Ok() {
			return ErrorInvalidJSON("[]StatshouseStoreTagFilter", "expected json array")
		}
		for ; !in.IsDelim(']'); index++ {
			if len(*vec) <= index {
				var newValue StatshouseStoreTagFilter
				*vec = append(*vec, newValue)
				*vec = (*vec)[:cap(*vec)]
			}
			if err := (*vec)[index].ReadJSONGeneral(jctx, in); err != nil {
				return err
			}
			in.WantComma()
		}
		in.Delim(']')
		if !in.Ok() {
			return ErrorInvalidJSON("[]StatshouseStoreTagFilter", "expected json array's end")
		}
	}
	*vec = (*vec)[:index]
	return nil
}

func BuiltinVectorStatshouseStoreTagFilterBoxedWriteJSON(w []byte, vec []StatshouseStoreTagFilter) []byte {
	return BuiltinVectorStatshouseStoreTagFilterBoxedWriteJSONOpt(nil, w, vec)
}
func BuiltinVectorStatshouseStoreTagFilterBoxedWriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte, vec []StatshouseStoreTagFilter) []byte {
	w = append(w, '[')
	for _, elem := range vec {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = elem.WriteJSONOpt(jctx, w)
	}
	return append(w, ']')
}

func BuiltinVectorStatshouseStoreTagFilterBoxedBytesFillRandom(rg *basictl.RandGenerator, vec *[]StatshouseStoreTagFilterBytes) {
	rg.IncreaseDepth()
	l := basictl.RandomSize(rg)
	*vec = make([]StatshouseStoreTagFilterBytes, l)
	for i := range *vec {
		(*vec)[i].FillRandom(rg)
	}
	rg.DecreaseDepth()
}
func BuiltinVectorStatshouseStoreTagFilterBoxedBytesReadTL1(w []byte, vec *[]StatshouseStoreTagFilterBytes) (_ []byte, err error) {
	var l uint32
	if w, err = basictl.NatRead(w, &l); err != nil {
		return w, err
	}
	if err = basictl.CheckLengthSanity(w, l, 4); err != nil {
		return w, err
	}
	if uint32(cap(*vec)) < l {
		*vec = make([]StatshouseStoreTagFilterBytes, l)
	} else {
		*vec = (*vec)[:l]
	}
	for i := range *vec {
		if w, err = (*vec)[i].ReadTL1Boxed(w); err != nil {
			return w, err
		}
	}
	return w, nil
}

func BuiltinVectorStatshouseStoreTagFilterBoxedBytesWriteTL1(w []byte, vec []StatshouseStoreTagFilterBytes) []byte {
	w = basictl.NatWrite(w, uint32(len(vec)))
	for _, elem := range vec {
		w = elem.WriteTL1Boxed(w)
	}
	return w
}

func BuiltinVectorStatshouseStoreTagFilterBoxedBytesInternalReadTL2(r []byte, vec *[]StatshouseStoreTagFilterBytes) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("[]StatshouseStoreTagFilterBytes")
}

func BuiltinVectorStatshouseStoreTagFilterBoxedBytesReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, vec *[]StatshouseStoreTagFilterBytes) error {
	*vec = (*vec)[:cap(*vec)]
	index := 0
	if in != nil {
		in.Delim('[')
		if !in.Ok() {
			return ErrorInvalidJSON("[]StatshouseStoreTagFilterBytes", "expected json array")
		}
		for ; !in.IsDelim(']'); index++ {
			if len(*vec) <= index {
				var newValue StatshouseStoreTagFilterBytes
				*vec = append(*vec, newValue)
				*vec = (*vec)[:cap(*vec)]
			}
			if err := (*vec)[index].ReadJSONGeneral(jctx, in); err != nil {
				return err
			}
			in.WantComma()
		}
		in.Delim(']')
		if !in.Ok() {
			return ErrorInvalidJSON("[]StatshouseStoreTagFilterBytes", "expected json array's end")
		}
	}
	*vec = (*vec)[:index]
	return nil
}

func BuiltinVectorStatshouseStoreTagFilterBoxedBytesWriteJSON(w []byte, vec []StatshouseStoreTagFilterBytes) []byte {
	return BuiltinVectorStatshouseStoreTagFilterBoxedBytesWriteJSONOpt(nil, w, vec)
}
func BuiltinVectorStatshouseStoreTagFilterBoxedBytesWriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte, vec []StatshouseStoreTagFilterBytes) []byte {
	w = append(w, '[')
	for _, elem := range vec {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = elem.WriteJSONOpt(jctx, w)
	}
	return append(w, ']')
}

// One tag predicate. Within a filter the mapped/values/empty/re2 arms are OR-ed
// for an IN filter and AND-ed for a NOT IN filter (what filterOperatorIn/NotIn do
// in internal/api/sql_query_series.go). re2 is unanchored RE2; values must bind
// as prepared statement parameters, never interpolate into SQL text.
type StatshouseStoreTagFilter struct {
	FieldsMask uint32
	// 0 .. format.MaxTags-1 (48)
	TagIndex int32
	// long, not int: carries a raw64 value whole
	Mapped []int64 // Conditional: item.FieldsMask.0
	// unmapped string values, matched against stagN
	Values []string // Conditional: item.FieldsMask.1
	// tagN = 0 AND stagN = ''
	// Empty (TrueType) // Conditional: item.FieldsMask.2
	Re2 string // Conditional: item.FieldsMask.3
}

func (StatshouseStoreTagFilter) TLName() string { return "statshouse.storeTagFilter" }
func (StatshouseStoreTagFilter) TLTag() uint32  { return 0x57cb1001 }

func (item *StatshouseStoreTagFilter) SetMapped(v []int64) {
	item.Mapped = v
	item.FieldsMask |= 1 << 0
}
func (item *StatshouseStoreTagFilter) ClearMapped() {
	item.Mapped = item.Mapped[:0]
	item.FieldsMask &^= 1 << 0
}
func (item *StatshouseStoreTagFilter) IsSetMapped() bool { return item.FieldsMask&(1<<0) != 0 }

func (item *StatshouseStoreTagFilter) SetValues(v []string) {
	item.Values = v
	item.FieldsMask |= 1 << 1
}
func (item *StatshouseStoreTagFilter) ClearValues() {
	item.Values = item.Values[:0]
	item.FieldsMask &^= 1 << 1
}
func (item *StatshouseStoreTagFilter) IsSetValues() bool { return item.FieldsMask&(1<<1) != 0 }

func (item *StatshouseStoreTagFilter) SetEmpty(v bool) {
	if v {
		item.FieldsMask |= 1 << 2
	} else {
		item.FieldsMask &^= 1 << 2
	}
}
func (item *StatshouseStoreTagFilter) IsSetEmpty() bool { return item.FieldsMask&(1<<2) != 0 }

func (item *StatshouseStoreTagFilter) SetRe2(v string) {
	item.Re2 = v
	item.FieldsMask |= 1 << 3
}
func (item *StatshouseStoreTagFilter) ClearRe2() {
	item.Re2 = ""
	item.FieldsMask &^= 1 << 3
}
func (item *StatshouseStoreTagFilter) IsSetRe2() bool { return item.FieldsMask&(1<<3) != 0 }

func (item *StatshouseStoreTagFilter) Reset() {
	item.FieldsMask = 0
	item.TagIndex = 0
	item.Mapped = item.Mapped[:0]
	item.Values = item.Values[:0]
	item.Re2 = ""
}

func (item *StatshouseStoreTagFilter) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b1111)
	item.TagIndex = basictl.RandomInt(rg)
	if item.FieldsMask&(1<<0) != 0 {
		BuiltinVectorLongFillRandom(rg, &item.Mapped)
	} else {
		item.Mapped = item.Mapped[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		BuiltinVectorStringFillRandom(rg, &item.Values)
	} else {
		item.Values = item.Values[:0]
	}
	if item.FieldsMask&(1<<3) != 0 {
		item.Re2 = basictl.RandomString(rg)
	} else {
		item.Re2 = ""
	}
}

func (item *StatshouseStoreTagFilter) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.TagIndex); err != nil {
		return w, err
	}
	if item.FieldsMask&(1<<0) != 0 {
		if w, err = BuiltinVectorLongReadTL1(w, &item.Mapped); err != nil {
			return w, err
		}
	} else {
		item.Mapped = item.Mapped[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		if w, err = BuiltinVectorStringReadTL1(w, &item.Values); err != nil {
			return w, err
		}
	} else {
		item.Values = item.Values[:0]
	}
	if item.FieldsMask&(1<<3) != 0 {
		if w, err = basictl.StringRead(w, &item.Re2); err != nil {
			return w, err
		}
	} else {
		item.Re2 = ""
	}
	return w, nil
}

func (item *StatshouseStoreTagFilter) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreTagFilter) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = basictl.IntWrite(w, item.TagIndex)
	if item.FieldsMask&(1<<0) != 0 {
		w = BuiltinVectorLongWriteTL1(w, item.Mapped)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = BuiltinVectorStringWriteTL1(w, item.Values)
	}
	if item.FieldsMask&(1<<3) != 0 {
		w = basictl.StringWrite(w, item.Re2)
	}
	return w
}

func (item *StatshouseStoreTagFilter) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1001); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreTagFilter) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreTagFilter) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1001)
	return item.WriteTL1(w)
}

func (item StatshouseStoreTagFilter) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreTagFilter) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreTagFilter) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propTagIndexPresented bool
	var propMappedPresented bool
	var propValuesPresented bool
	var propEmptyPresented bool
	var trueTypeEmptyValue bool
	var propRe2Presented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "tag_index":
				if propTagIndexPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "tag_index")
				}
				propTagIndexPresented = true
				if err := Json2ReadInt32(in, &item.TagIndex); err != nil {
					return err
				}
			case "mapped":
				if propMappedPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "mapped")
				}
				propMappedPresented = true
				if err := BuiltinVectorLongReadJSONGeneral(jctx, in, &item.Mapped); err != nil {
					return err
				}
			case "values":
				if propValuesPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "values")
				}
				propValuesPresented = true
				if err := BuiltinVectorStringReadJSONGeneral(jctx, in, &item.Values); err != nil {
					return err
				}
			case "empty":
				if propEmptyPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "empty")
				}
				propEmptyPresented = true
				if err := Json2ReadBool(in, &trueTypeEmptyValue); err != nil {
					return err
				}
			case "re2":
				if propRe2Presented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "re2")
				}
				propRe2Presented = true
				if err := Json2ReadString(in, &item.Re2); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeTagFilter", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propTagIndexPresented {
		item.TagIndex = 0
	}
	if !propMappedPresented {
		item.Mapped = item.Mapped[:0]
	}
	if !propValuesPresented {
		item.Values = item.Values[:0]
	}
	if !propRe2Presented {
		item.Re2 = ""
	}
	if propMappedPresented {
		item.FieldsMask |= 1 << 0
	}
	if propValuesPresented {
		item.FieldsMask |= 1 << 1
	}
	if trueTypeEmptyValue {
		item.FieldsMask |= 1 << 2
	}
	if propRe2Presented {
		item.FieldsMask |= 1 << 3
	}
	if propEmptyPresented && !trueTypeEmptyValue && (item.FieldsMask&(1<<2) != 0) {
		return ErrorInvalidJSON("statshouse.storeTagFilter", "field 'empty' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 2 is 1")
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreTagFilter) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreTagFilter) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreTagFilter) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexTagIndex := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"tag_index":`...)
	w = basictl.JSONWriteInt32(w, item.TagIndex)
	if !(item.TagIndex != 0) {
		w = w[:backupIndexTagIndex]
	}
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"mapped":`...)
		w = BuiltinVectorLongWriteJSONOpt(jctx, w, item.Mapped)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"values":`...)
		w = BuiltinVectorStringWriteJSONOpt(jctx, w, item.Values)
	}
	if item.FieldsMask&(1<<2) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"empty":true`...)
	}
	if item.FieldsMask&(1<<3) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"re2":`...)
		w = basictl.JSONWriteString(w, item.Re2)
	}
	return append(w, '}')
}

func (item *StatshouseStoreTagFilter) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreTagFilter) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeTagFilter", err.Error())
	}
	return nil
}

func (item *StatshouseStoreTagFilter) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeTagFilter"))
}

func (item *StatshouseStoreTagFilter) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeTagFilter")
}

// One tag predicate. Within a filter the mapped/values/empty/re2 arms are OR-ed
// for an IN filter and AND-ed for a NOT IN filter (what filterOperatorIn/NotIn do
// in internal/api/sql_query_series.go). re2 is unanchored RE2; values must bind
// as prepared statement parameters, never interpolate into SQL text.
type StatshouseStoreTagFilterBytes struct {
	FieldsMask uint32
	// 0 .. format.MaxTags-1 (48)
	TagIndex int32
	// long, not int: carries a raw64 value whole
	Mapped []int64 // Conditional: item.FieldsMask.0
	// unmapped string values, matched against stagN
	Values [][]byte // Conditional: item.FieldsMask.1
	// tagN = 0 AND stagN = ''
	// Empty (TrueType) // Conditional: item.FieldsMask.2
	Re2 []byte // Conditional: item.FieldsMask.3
}

func (StatshouseStoreTagFilterBytes) TLName() string { return "statshouse.storeTagFilter" }
func (StatshouseStoreTagFilterBytes) TLTag() uint32  { return 0x57cb1001 }

func (item *StatshouseStoreTagFilterBytes) SetMapped(v []int64) {
	item.Mapped = v
	item.FieldsMask |= 1 << 0
}
func (item *StatshouseStoreTagFilterBytes) ClearMapped() {
	item.Mapped = item.Mapped[:0]
	item.FieldsMask &^= 1 << 0
}
func (item *StatshouseStoreTagFilterBytes) IsSetMapped() bool { return item.FieldsMask&(1<<0) != 0 }

func (item *StatshouseStoreTagFilterBytes) SetValues(v [][]byte) {
	item.Values = v
	item.FieldsMask |= 1 << 1
}
func (item *StatshouseStoreTagFilterBytes) ClearValues() {
	item.Values = item.Values[:0]
	item.FieldsMask &^= 1 << 1
}
func (item *StatshouseStoreTagFilterBytes) IsSetValues() bool { return item.FieldsMask&(1<<1) != 0 }

func (item *StatshouseStoreTagFilterBytes) SetEmpty(v bool) {
	if v {
		item.FieldsMask |= 1 << 2
	} else {
		item.FieldsMask &^= 1 << 2
	}
}
func (item *StatshouseStoreTagFilterBytes) IsSetEmpty() bool { return item.FieldsMask&(1<<2) != 0 }

func (item *StatshouseStoreTagFilterBytes) SetRe2(v []byte) {
	item.Re2 = v
	item.FieldsMask |= 1 << 3
}
func (item *StatshouseStoreTagFilterBytes) ClearRe2() {
	item.Re2 = item.Re2[:0]
	item.FieldsMask &^= 1 << 3
}
func (item *StatshouseStoreTagFilterBytes) IsSetRe2() bool { return item.FieldsMask&(1<<3) != 0 }

func (item *StatshouseStoreTagFilterBytes) Reset() {
	item.FieldsMask = 0
	item.TagIndex = 0
	item.Mapped = item.Mapped[:0]
	item.Values = item.Values[:0]
	item.Re2 = item.Re2[:0]
}

func (item *StatshouseStoreTagFilterBytes) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b1111)
	item.TagIndex = basictl.RandomInt(rg)
	if item.FieldsMask&(1<<0) != 0 {
		BuiltinVectorLongFillRandom(rg, &item.Mapped)
	} else {
		item.Mapped = item.Mapped[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		BuiltinVectorStringBytesFillRandom(rg, &item.Values)
	} else {
		item.Values = item.Values[:0]
	}
	if item.FieldsMask&(1<<3) != 0 {
		item.Re2 = basictl.RandomStringBytes(rg)
	} else {
		item.Re2 = item.Re2[:0]
	}
}

func (item *StatshouseStoreTagFilterBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.TagIndex); err != nil {
		return w, err
	}
	if item.FieldsMask&(1<<0) != 0 {
		if w, err = BuiltinVectorLongReadTL1(w, &item.Mapped); err != nil {
			return w, err
		}
	} else {
		item.Mapped = item.Mapped[:0]
	}
	if item.FieldsMask&(1<<1) != 0 {
		if w, err = BuiltinVectorStringBytesReadTL1(w, &item.Values); err != nil {
			return w, err
		}
	} else {
		item.Values = item.Values[:0]
	}
	if item.FieldsMask&(1<<3) != 0 {
		if w, err = basictl.StringReadBytes(w, &item.Re2); err != nil {
			return w, err
		}
	} else {
		item.Re2 = item.Re2[:0]
	}
	return w, nil
}

func (item *StatshouseStoreTagFilterBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreTagFilterBytes) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = basictl.IntWrite(w, item.TagIndex)
	if item.FieldsMask&(1<<0) != 0 {
		w = BuiltinVectorLongWriteTL1(w, item.Mapped)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = BuiltinVectorStringBytesWriteTL1(w, item.Values)
	}
	if item.FieldsMask&(1<<3) != 0 {
		w = basictl.StringWriteBytes(w, item.Re2)
	}
	return w
}

func (item *StatshouseStoreTagFilterBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1001); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreTagFilterBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreTagFilterBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1001)
	return item.WriteTL1(w)
}

func (item StatshouseStoreTagFilterBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreTagFilterBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreTagFilterBytes) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propTagIndexPresented bool
	var propMappedPresented bool
	var propValuesPresented bool
	var propEmptyPresented bool
	var trueTypeEmptyValue bool
	var propRe2Presented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "tag_index":
				if propTagIndexPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "tag_index")
				}
				propTagIndexPresented = true
				if err := Json2ReadInt32(in, &item.TagIndex); err != nil {
					return err
				}
			case "mapped":
				if propMappedPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "mapped")
				}
				propMappedPresented = true
				if err := BuiltinVectorLongReadJSONGeneral(jctx, in, &item.Mapped); err != nil {
					return err
				}
			case "values":
				if propValuesPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "values")
				}
				propValuesPresented = true
				if err := BuiltinVectorStringBytesReadJSONGeneral(jctx, in, &item.Values); err != nil {
					return err
				}
			case "empty":
				if propEmptyPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "empty")
				}
				propEmptyPresented = true
				if err := Json2ReadBool(in, &trueTypeEmptyValue); err != nil {
					return err
				}
			case "re2":
				if propRe2Presented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagFilter", "re2")
				}
				propRe2Presented = true
				if err := Json2ReadStringBytes(in, &item.Re2); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeTagFilter", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propTagIndexPresented {
		item.TagIndex = 0
	}
	if !propMappedPresented {
		item.Mapped = item.Mapped[:0]
	}
	if !propValuesPresented {
		item.Values = item.Values[:0]
	}
	if !propRe2Presented {
		item.Re2 = item.Re2[:0]
	}
	if propMappedPresented {
		item.FieldsMask |= 1 << 0
	}
	if propValuesPresented {
		item.FieldsMask |= 1 << 1
	}
	if trueTypeEmptyValue {
		item.FieldsMask |= 1 << 2
	}
	if propRe2Presented {
		item.FieldsMask |= 1 << 3
	}
	if propEmptyPresented && !trueTypeEmptyValue && (item.FieldsMask&(1<<2) != 0) {
		return ErrorInvalidJSON("statshouse.storeTagFilter", "field 'empty' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 2 is 1")
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreTagFilterBytes) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreTagFilterBytes) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreTagFilterBytes) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexTagIndex := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"tag_index":`...)
	w = basictl.JSONWriteInt32(w, item.TagIndex)
	if !(item.TagIndex != 0) {
		w = w[:backupIndexTagIndex]
	}
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"mapped":`...)
		w = BuiltinVectorLongWriteJSONOpt(jctx, w, item.Mapped)
	}
	if item.FieldsMask&(1<<1) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"values":`...)
		w = BuiltinVectorStringBytesWriteJSONOpt(jctx, w, item.Values)
	}
	if item.FieldsMask&(1<<2) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"empty":true`...)
	}
	if item.FieldsMask&(1<<3) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"re2":`...)
		w = basictl.JSONWriteStringBytes(w, item.Re2)
	}
	return append(w, '}')
}

func (item *StatshouseStoreTagFilterBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreTagFilterBytes) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeTagFilter", err.Error())
	}
	return nil
}

func (item *StatshouseStoreTagFilterBytes) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeTagFilter"))
}

func (item *StatshouseStoreTagFilterBytes) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeTagFilter")
}
