// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

// The tag-values verb, covering both the values and the ids-only mode.
//
// CRITICAL: the aggregator MUST NOT apply the user's top-N. A value ranked below
// N on every individual shard can still be globally top-N once counts are
// summed, so per-shard top-N silently returns wrong answers. The aggregator
// returns ALL values up to row_limit (a safety cap, not the user's N) and fails
// on truncation; the API sums counts across shards and takes the global top N.
type StatshouseStoreQueryTagValues struct {
	FieldsMask uint32
	Base       StatshouseStoreQueryBase
	TagIndex   int32
	// ids-only mode
	// IdsOnly (TrueType) // Conditional: item.FieldsMask.0
}

func (StatshouseStoreQueryTagValues) TLName() string { return "statshouse.storeQueryTagValues" }
func (StatshouseStoreQueryTagValues) TLTag() uint32  { return 0x57cb1009 }

func (item *StatshouseStoreQueryTagValues) SetIdsOnly(v bool) {
	if v {
		item.FieldsMask |= 1 << 0
	} else {
		item.FieldsMask &^= 1 << 0
	}
}
func (item *StatshouseStoreQueryTagValues) IsSetIdsOnly() bool { return item.FieldsMask&(1<<0) != 0 }

func (item *StatshouseStoreQueryTagValues) Reset() {
	item.FieldsMask = 0
	item.Base.Reset()
	item.TagIndex = 0
}

func (item *StatshouseStoreQueryTagValues) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b1)
	item.Base.FillRandom(rg)
	item.TagIndex = basictl.RandomInt(rg)
}

func (item *StatshouseStoreQueryTagValues) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = item.Base.ReadTL1(w); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.TagIndex); err != nil {
		return w, err
	}
	return w, nil
}

func (item *StatshouseStoreQueryTagValues) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreQueryTagValues) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Base.WriteTL1(w)
	w = basictl.IntWrite(w, item.TagIndex)
	return w
}

func (item *StatshouseStoreQueryTagValues) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1009); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreQueryTagValues) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreQueryTagValues) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1009)
	return item.WriteTL1(w)
}

func (item *StatshouseStoreQueryTagValues) ReadResultTL1(w []byte, ret *StatshouseStoreTagValuesResponse) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseStoreQueryTagValues) WriteResultTL1(w []byte, ret StatshouseStoreTagValuesResponse) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseStoreQueryTagValues) ReadResultJSON(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, ret *StatshouseStoreTagValuesResponse) error {
	if err := ret.ReadJSONGeneral(jctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseStoreQueryTagValues) WriteResultJSON(w []byte, ret StatshouseStoreTagValuesResponse) (_ []byte, err error) {
	return item.writeResultJSON(nil, w, ret)
}

func (item *StatshouseStoreQueryTagValues) writeResultJSON(jctx *basictl.JSONWriteContext, w []byte, ret StatshouseStoreTagValuesResponse) (_ []byte, err error) {
	w = ret.WriteJSONOpt(jctx, w)
	return w, nil
}

func (item *StatshouseStoreQueryTagValues) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret StatshouseStoreTagValuesResponse
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseStoreQueryTagValues) ReadResultTL1WriteResultJSON(jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreTagValuesResponse
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(jctx, w, ret)
	return r, w, err
}

func (item *StatshouseStoreQueryTagValues) ReadResultJSONWriteResultTL1(jctx *basictl.JSONReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreTagValuesResponse
	if err = item.ReadResultJSON(jctx, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseStoreQueryTagValues) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues")
}

func (item *StatshouseStoreQueryTagValues) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues")
}

func (item *StatshouseStoreQueryTagValues) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues")
}

func (item *StatshouseStoreQueryTagValues) ReadResultJSONWriteResultTL2(jctx *basictl.JSONReadContext, tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues")
}

func (item StatshouseStoreQueryTagValues) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreQueryTagValues) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreQueryTagValues) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propBasePresented bool
	var propTagIndexPresented bool
	var propIdsOnlyPresented bool
	var trueTypeIdsOnlyValue bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryTagValues", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "base":
				if propBasePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryTagValues", "base")
				}
				propBasePresented = true
				if err := item.Base.ReadJSONGeneral(jctx, in); err != nil {
					return err
				}
			case "tag_index":
				if propTagIndexPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryTagValues", "tag_index")
				}
				propTagIndexPresented = true
				if err := Json2ReadInt32(in, &item.TagIndex); err != nil {
					return err
				}
			case "ids_only":
				if propIdsOnlyPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryTagValues", "ids_only")
				}
				propIdsOnlyPresented = true
				if err := Json2ReadBool(in, &trueTypeIdsOnlyValue); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeQueryTagValues", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propBasePresented {
		item.Base.Reset()
	}
	if !propTagIndexPresented {
		item.TagIndex = 0
	}
	if trueTypeIdsOnlyValue {
		item.FieldsMask |= 1 << 0
	}
	if propIdsOnlyPresented && !trueTypeIdsOnlyValue && (item.FieldsMask&(1<<0) != 0) {
		return ErrorInvalidJSON("statshouse.storeQueryTagValues", "field 'ids_only' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 0 is 1")
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreQueryTagValues) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreQueryTagValues) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreQueryTagValues) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"base":`...)
	w = item.Base.WriteJSONOpt(jctx, w)
	backupIndexTagIndex := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"tag_index":`...)
	w = basictl.JSONWriteInt32(w, item.TagIndex)
	if !(item.TagIndex != 0) {
		w = w[:backupIndexTagIndex]
	}
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"ids_only":true`...)
	}
	return append(w, '}')
}

func (item *StatshouseStoreQueryTagValues) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreQueryTagValues) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeQueryTagValues", err.Error())
	}
	return nil
}

func (item *StatshouseStoreQueryTagValues) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues"))
}

func (item *StatshouseStoreQueryTagValues) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues")
}

// The tag-values verb, covering both the values and the ids-only mode.
//
// CRITICAL: the aggregator MUST NOT apply the user's top-N. A value ranked below
// N on every individual shard can still be globally top-N once counts are
// summed, so per-shard top-N silently returns wrong answers. The aggregator
// returns ALL values up to row_limit (a safety cap, not the user's N) and fails
// on truncation; the API sums counts across shards and takes the global top N.
type StatshouseStoreQueryTagValuesBytes struct {
	FieldsMask uint32
	Base       StatshouseStoreQueryBaseBytes
	TagIndex   int32
	// ids-only mode
	// IdsOnly (TrueType) // Conditional: item.FieldsMask.0
}

func (StatshouseStoreQueryTagValuesBytes) TLName() string { return "statshouse.storeQueryTagValues" }
func (StatshouseStoreQueryTagValuesBytes) TLTag() uint32  { return 0x57cb1009 }

func (item *StatshouseStoreQueryTagValuesBytes) SetIdsOnly(v bool) {
	if v {
		item.FieldsMask |= 1 << 0
	} else {
		item.FieldsMask &^= 1 << 0
	}
}
func (item *StatshouseStoreQueryTagValuesBytes) IsSetIdsOnly() bool {
	return item.FieldsMask&(1<<0) != 0
}

func (item *StatshouseStoreQueryTagValuesBytes) Reset() {
	item.FieldsMask = 0
	item.Base.Reset()
	item.TagIndex = 0
}

func (item *StatshouseStoreQueryTagValuesBytes) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b1)
	item.Base.FillRandom(rg)
	item.TagIndex = basictl.RandomInt(rg)
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = item.Base.ReadTL1(w); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.TagIndex); err != nil {
		return w, err
	}
	return w, nil
}

func (item *StatshouseStoreQueryTagValuesBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreQueryTagValuesBytes) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Base.WriteTL1(w)
	w = basictl.IntWrite(w, item.TagIndex)
	return w
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1009); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreQueryTagValuesBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreQueryTagValuesBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1009)
	return item.WriteTL1(w)
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadResultTL1(w []byte, ret *StatshouseStoreTagValuesResponseBytes) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseStoreQueryTagValuesBytes) WriteResultTL1(w []byte, ret StatshouseStoreTagValuesResponseBytes) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadResultJSON(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, ret *StatshouseStoreTagValuesResponseBytes) error {
	if err := ret.ReadJSONGeneral(jctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseStoreQueryTagValuesBytes) WriteResultJSON(w []byte, ret StatshouseStoreTagValuesResponseBytes) (_ []byte, err error) {
	return item.writeResultJSON(nil, w, ret)
}

func (item *StatshouseStoreQueryTagValuesBytes) writeResultJSON(jctx *basictl.JSONWriteContext, w []byte, ret StatshouseStoreTagValuesResponseBytes) (_ []byte, err error) {
	w = ret.WriteJSONOpt(jctx, w)
	return w, nil
}

func (item *StatshouseStoreQueryTagValuesBytes) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret StatshouseStoreTagValuesResponseBytes
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadResultTL1WriteResultJSON(jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreTagValuesResponseBytes
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(jctx, w, ret)
	return r, w, err
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadResultJSONWriteResultTL1(jctx *basictl.JSONReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseStoreTagValuesResponseBytes
	if err = item.ReadResultJSON(jctx, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues")
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues")
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues")
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadResultJSONWriteResultTL2(jctx *basictl.JSONReadContext, tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues")
}

func (item StatshouseStoreQueryTagValuesBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propBasePresented bool
	var propTagIndexPresented bool
	var propIdsOnlyPresented bool
	var trueTypeIdsOnlyValue bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryTagValues", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "base":
				if propBasePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryTagValues", "base")
				}
				propBasePresented = true
				if err := item.Base.ReadJSONGeneral(jctx, in); err != nil {
					return err
				}
			case "tag_index":
				if propTagIndexPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryTagValues", "tag_index")
				}
				propTagIndexPresented = true
				if err := Json2ReadInt32(in, &item.TagIndex); err != nil {
					return err
				}
			case "ids_only":
				if propIdsOnlyPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeQueryTagValues", "ids_only")
				}
				propIdsOnlyPresented = true
				if err := Json2ReadBool(in, &trueTypeIdsOnlyValue); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeQueryTagValues", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propBasePresented {
		item.Base.Reset()
	}
	if !propTagIndexPresented {
		item.TagIndex = 0
	}
	if trueTypeIdsOnlyValue {
		item.FieldsMask |= 1 << 0
	}
	if propIdsOnlyPresented && !trueTypeIdsOnlyValue && (item.FieldsMask&(1<<0) != 0) {
		return ErrorInvalidJSON("statshouse.storeQueryTagValues", "field 'ids_only' is explicitly set to false, but corresponding fieldmask item.FieldsMask bit 0 is 1")
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreQueryTagValuesBytes) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreQueryTagValuesBytes) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreQueryTagValuesBytes) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"base":`...)
	w = item.Base.WriteJSONOpt(jctx, w)
	backupIndexTagIndex := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"tag_index":`...)
	w = basictl.JSONWriteInt32(w, item.TagIndex)
	if !(item.TagIndex != 0) {
		w = w[:backupIndexTagIndex]
	}
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"ids_only":true`...)
	}
	return append(w, '}')
}

func (item *StatshouseStoreQueryTagValuesBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreQueryTagValuesBytes) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeQueryTagValues", err.Error())
	}
	return nil
}

func (item *StatshouseStoreQueryTagValuesBytes) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues"))
}

func (item *StatshouseStoreQueryTagValuesBytes) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeQueryTagValues")
}
