// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

// Per-tag storage interpretation as the API resolved it from ITS journal:
// 0 = mapped  tagN holds a mapping id, stagN may hold an unmapped string
// 1 = raw32   tagN holds the value directly, stagN unused
// 2 = raw64   value SPLIT: low half in tagN, high half in tagN+1
// The aggregator validates against its own journal at metric_version and
// returns metadata_mismatch on disagreement — it never reinterprets rows.
type StatshouseStoreTagLayout struct {
	Kinds []int32
}

func (StatshouseStoreTagLayout) TLName() string { return "statshouse.storeTagLayout" }
func (StatshouseStoreTagLayout) TLTag() uint32  { return 0x57cb1002 }

func (item *StatshouseStoreTagLayout) Reset() {
	item.Kinds = item.Kinds[:0]
}

func (item *StatshouseStoreTagLayout) FillRandom(rg *basictl.RandGenerator) {
	BuiltinVectorIntFillRandom(rg, &item.Kinds)
}

func (item *StatshouseStoreTagLayout) ReadTL1(w []byte) (_ []byte, err error) {
	return BuiltinVectorIntReadTL1(w, &item.Kinds)
}

func (item *StatshouseStoreTagLayout) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseStoreTagLayout) WriteTL1(w []byte) []byte {
	w = BuiltinVectorIntWriteTL1(w, item.Kinds)
	return w
}

func (item *StatshouseStoreTagLayout) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x57cb1002); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseStoreTagLayout) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseStoreTagLayout) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x57cb1002)
	return item.WriteTL1(w)
}

func (item StatshouseStoreTagLayout) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseStoreTagLayout) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *StatshouseStoreTagLayout) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propKindsPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "kinds":
				if propKindsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.storeTagLayout", "kinds")
				}
				propKindsPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(jctx, in, &item.Kinds); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.storeTagLayout", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propKindsPresented {
		item.Kinds = item.Kinds[:0]
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseStoreTagLayout) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *StatshouseStoreTagLayout) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *StatshouseStoreTagLayout) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexKinds := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"kinds":`...)
	w = BuiltinVectorIntWriteJSONOpt(jctx, w, item.Kinds)
	if !(len(item.Kinds) != 0) {
		w = w[:backupIndexKinds]
	}
	return append(w, '}')
}

func (item *StatshouseStoreTagLayout) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseStoreTagLayout) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.storeTagLayout", err.Error())
	}
	return nil
}

func (item *StatshouseStoreTagLayout) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.storeTagLayout"))
}

func (item *StatshouseStoreTagLayout) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.storeTagLayout")
}
